%% Copernicus Publications Manuscript Preparation Template for LaTeX Submissions
%% ---------------------------------
%% This template should be used for copernicus.cls
%% The class file and some style files are bundled in the Copernicus Latex Package, which can be downloaded from the different journal webpages.
%% For further assistance please contact Copernicus Publications at: production@copernicus.org
%% https://publications.copernicus.org/for_authors/manuscript_preparation.html

%% copernicus_rticles_template (flag for rticles template detection - do not remove!)

%% Please use the following documentclass and journal abbreviations for discussion papers and final revised papers.

%% 2-column papers and discussion papers
\documentclass[, manuscript]{copernicus}



%% Journal abbreviations (please use the same for preprints and final revised papers)

% Advances in Geosciences (adgeo)
% Advances in Radio Science (ars)
% Advances in Science and Research (asr)
% Advances in Statistical Climatology, Meteorology and Oceanography (ascmo)
% Aerosol Research (ar)
% Annales Geophysicae (angeo)
% Archives Animal Breeding (aab)
% Atmospheric Chemistry and Physics (acp)
% Atmospheric Measurement Techniques (amt)
% Biogeosciences (bg)
% Climate of the Past (cp)
% DEUQUA Special Publications (deuquasp)
% Earth Surface Dynamics (esurf)
% Earth System Dynamics (esd)
% Earth System Science Data (essd)
% E&G Quaternary Science Journal (egqsj)
% EGUsphere (egusphere) | This is only for EGUsphere preprints submitted without relation to an EGU journal.
% European Journal of Mineralogy (ejm)
% Fossil Record (fr)
% Geochronology (gchron)
% Geographica Helvetica (gh)
% Geoscience Communication (gc)
% Geoscientific Instrumentation, Methods and Data Systems (gi)
% Geoscientific Model Development (gmd)
% History of Geo- and Space Sciences (hgss)
% Hydrology and Earth System Sciences (hess)
% Journal of Bone and Joint Infection (jbji)
% Journal of Micropalaeontology (jm)
% Journal of Sensors and Sensor Systems (jsss)
% Magnetic Resonance (mr)
% Mechanical Sciences (ms)
% Natural Hazards and Earth System Sciences (nhess)
% Nonlinear Processes in Geophysics (npg)
% Ocean Science (os)
% Polarforschung - Journal of the German Society for Polar Research (polf)
% Primate Biology (pb)
% Proceedings of the International Association of Hydrological Sciences (piahs)
% Safety of Nuclear Waste Disposal (sand)
% Scientific Drilling (sd)
% SOIL (soil)
% Solid Earth (se)
% State of the Planet (sp)
% The Cryosphere (tc)
% Weather and Climate Dynamics (wcd)
% Web Ecology (we)
% Wind Energy Science (wes)

% Pandoc citation processing

% The "Technical instructions for LaTex" by Copernicus require _not_ to insert any additional packages.
% 
% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}


%%\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
%
%% \usepackage commands included in the copernicus.cls:
%\usepackage[german, english]{babel}
%\usepackage{tabularx}
%\usepackage{cancel}
%\usepackage{multirow}
%\usepackage{supertabular}
%\usepackage{algorithmic}
%\usepackage{algorithm}
%\usepackage{amsthm}
%\usepackage{float}
%\usepackage{subfig}
%\usepackage{rotating}

\begin{document}


\title{Incorporating observed fire severity in refined emissions
estimates for boreal and temperate forest fires in the carbon budget
model CBM-CFS3}


\Author[1]{Dan K.}{Thompson}
\Author[2]{Ellen}{Whitman}
\Author[3]{Hafer}{Mark}
\Author[2]{Oleksandra}{Hararuk}
\Author[1]{Chelene}{Hanes}
\Author[3]{Vinicius}{Manvailer Goncalves}
\Author[3]{Ben}{Hudson}


\affil[1]{Natural Resources Canada, Canadian Forest Service, Great Lakes
Forestry Centre, Sault Ste. Marie, Canada}
\affil[2]{Natural Resources Canada, Canadian Forest Service, Northern
Forestry Centre, Edmonton, Canada}
\affil[3]{Natural Resources Canada, Canadian Forest Service, Pacific
Forestry Centre, Victoria, Canada}

\runningtitle{Fire Severity and Canadian Forest GHG Reporting}

\runningauthor{Thompson et al.}





\received{}
\pubdiscuss{} %% only important for two-stage journals
\revised{}
\accepted{}
\published{}

%% These dates will be inserted by Copernicus Publications during the typesetting process.


\firstpage{1}

\maketitle


\begin{abstract}
Among the many natural disturbances that affect Canada's boreal and
temperate forest biomes, wildfire has the greatest impact on forest
productivity, landscape structure, timber supply and greenhouse gas
emissions. Fire severity represents the fate of biomass, partioning
survival, consumption, and mortality without consumption. Currently, the
impact of fire on carbon stocks is limited to a single parametrization
of fire severity that assumes only high severity fires, despite evidence
of widespread mixed-severity fires. This paper describes a sub-model,
termed FireDMs (Fire Disturbance Matrix: severity), of the National
Forest Carbon Monitoring Accounting and Reporting System for Canada
(NFCMARS). In this sub-model, field measurements of biomass consumption
are related to satellite-derived burn severity maps and are interpreted
from a fire physics and ecology perspective to derive estimates of the
forest greenhouse gas emissions in the immediate aftermath of fires. The
sub-model also quantifies fire-killed but uncombusted biomass as a set
of disctinct pools. Model outputs indicate total direct carbon emissions
range from a 11 t C/ha in Boreal Shield West forests of Saskatchewan
following low severity fire to over 60 t C/ha in Pacific Maritime
forests of British Columbia under high severity fire. The existing
approach to emissions in NFC-MARS yields regional CO2e emissions that
are 10 to 25 percent higher than this new method, owing to lower overall
canopy consumption with mixed-severity fires, which is only partially
offset by increased estimates of forest floor consumption in this new
approach. Comparisons against directly observed fire plume emissions
ratios as well as against annualized carbon emissions for Canada's 2023
fire season show good model agreement with observations.
\end{abstract}


\copyrightstatement{His Majesty the King in Right of Canada as
represented by the Minister of Natural Resources Canada. This work is
distributed under the Creative Commons Attribution 4.0 License.}


\section{Introduction}

Wildfire is on par with insects as the largest stand-replacing
disturbance process in Canada's forest, impacting \textasciitilde1--3
Mha of Canada's 367 Mha forested area in a typical year
\citep{hanes2019}. In Canada's updated 54-year burned area record, ten
years have exceeded 4 Mha of burned area (or approximately 1\% of
Canada's forest area) \citep{skakun2022}. The 2023 fire season in Canada
burned a remarkable 15 Mha owing to extreme drought, severe fire weather
conditions, and a prolonged fire season length
\citep{jainDriversImpactsRecordBreaking2024}.

Managed northern forest areas, adjacent to communities, have shown the
effects of local suppression leading to a stand age bias towards older
stands; though the effect is largely limited to a c.~25 km radius around
these widely dispersed communities \citep{parisien2020}. More southern
boreal forest with extensive suppression activities has historically
seen evidence of a reduction in observed vs potential area burned
\citep{cummingEffectiveFireSuppression2005} though this effect has
likely been erased given the increasing frequency of extreme burning
conditions \citet{wangCriticalFireWeather2023} and corresponding record
area burned \citep{jainDriversImpactsRecordBreaking2024}.

Burned area in Canada is dominated by a relatively small number of very
large fires, with 3\% of fires constituting 97\% of the burned area
\citep{stocks2002}. Lightning-caused fires account for approximately
half of all ignitions and approximately 80\% of burned area, but no
distinction is made between human and lightning ignition for forest
sector GHG reporting purposes. Annual burned area mapping for GHG
reporting in Canada is conducted using a composite of satellite and
aerial mapping at 30 metre resolution \citep{hall2020}; the relatively
small number of large fires, and their slow vegetation regeneration
\citep{white2017} allows for reliable mapping using multispectral
imagery such as Landsat within one year of the fire \citep{whitman2018}.

Canada reports on GHG emission and removals from the forest sector in
Canada's National GHG Inventory Report (NIR). Carbon stocks and stock
changes are modelled using the Carbon Budget Model of the Canadian
Forest Sector (CBM-CFS3) \citep{kurzCBMCFS3ModelCarbondynamics2009}
parameterized and driven by spatial and non-spatial data describing
forest inventory, annual yield and disturbance
\citep{stinsonInventorybasedAnalysisCanadas2011}. Following
international good practice guidance to focus on human-caused emissions
in NIRs, Canada focuses emission reporting on managed forest lands,
which make up approximately 225 Mha of Canada's 367 Mha total forest
area. In CBM-CFS3, forest inventory is represented by spatially
referenced stand lists representing large homogeneous stands that fall
within spatial units (e.g.~forest management areas) and broad regions
called Reconciliation Units (RU) that are the intersection of ecozones
with provincial/territorial boundaries \citep{kurz2002}. Within CBM-CFS3
precisely mapped burned areas are summarized at the level of spatial
units and applied randomly to stands within that unit.

Large wildfire burned area is not distributed equally across differing
forest management regimes in Canada. Managed forest, where GHG emissions
reporting is mandated, accounts for 23\% of the area burned between 1972
and 2024; these publicly-owned managed forest areas under long-term
license to private timber companies forms 40\% of Canada's forest area
\citep{stinson2019}. Privately-owned forest constitutes 6\% of the
forest area, but only 0.5\% of area burned. The large majority (c.~75\%)
of the forest area burned in Canada occurs in a mix of formally
protected areas, remote unmanaged forest, Indigenous reserve lands and
other uses without large-scale harvesting. In these areas, detailed GHG
reporting is required only in protected areas.

Years with larger burned areas will improve the representative nature of
random stands being assigned fire disturbance within a year, as a wider
variety of stand types will be selected. Furthermore, large,
drought-driven fire years such as 2023 have been observed to burn at
more equal rates across the diversity of local ecosite flammability
\citep{parks2018, whitman2024} and thus provides an ideal test case for
assessing changes in emissions estimates for a spatially referenced
system. Importantly, these years with very large area burned still show
a similar natural range in variability of burn severity
\citep{whitman2018}.

CBM-CFS3 currently assesses fire impacts to carbon pools only as
representing high-severity fire, which is the most common of the three
severity classes (low, moderate, and high) used for assessing of burned
forest in Canada \citep{hall2008} and the conterminous US
\citep{eidenshink2007}. Biomass consumption estimates in CBM-CFS3 are
based on the assumption of 100\% crown consumption of conifer fuels,
with additional biomass consumption following a spatially-referenced
aggregated estimate at the RU-level of annualized drought conditions.
Biomass consumption estimates for the remaining forest carbon pools are
made via the Canadian Fire Behaviour Prediction System (FBP;
\citet{forestrycanadafiredangerratinggroup1992}) based on the fire's
start date fire weather conditions. Though the FBP is able to simulate
fire behaviour along the entire intensity gradient from surface to crown
fire, the lack of fire severity mapping and biomass consumption rates
along at different severity classes has constrained carbon modelling to
the most common high severity class.

Quantification of the change in carbon stock in CBM-CFS3 is made via a
``Disturbance Matrix'' (hereafter referred to as a DM) which is a matrix
of coefficients between 0 and 1, where rows are donor pools, and
columns: receptor pools or gases that are generated by a fire.
Atmospheric fluxes of CO\textsubscript{2}, CO, and CH\textsubscript{4}
are also tracked in the DM. Importantly, unlike emissions-only fire
models commonly used in air quality modelling in Canada
\citep{chen2019}, DM definitions in CBM-CFS3 also track the transfer of
live biomass to dead, but still uncombusted pools, such as the transfer
from live stemwood pools (which are killed but not burned) to standing
deadwood, also known as snags.

Although DMs may provide a more conservative estimate of C emissions due
to not combusting all biomass instantaneously, it may overestimate the C
emissions due to assuming uniform fire severity. In Canada's forests, a
combination of climate, disturbance history, soils, and less frequently
topographic variables determine leading tree species; at local scales
(1--100 ha), tree species composition plays a major role in determining
ecosystem susceptibility to fire \citep{bernier2016} where older,
conifer-dominated forests burn at very high rates relative to adjacent
deciduous or mixed stands. Large drought-driven fire years may increase
burn rates in deciduous and mixed forest to levels similar to older
conifer stands\citep{parksNewMetricQuantifying2014}. However, even in
more intense drought conditions, deciduous and mixed forest burn rates
are still consistently lower than in most conifer forests - except xeric
conifer forest which tend to be more fire resistant \citep{whitman2018}.
Thus, important local biases in fire activity and severity towards older
and moderate to poorly-drained forests are not resolved in the
spatially-referenced CBM-CFS3 when a uniform fire severity is applied.

To support recent advances in operational burn severity mapping for
Canada \citep{whitman2020} alongside multi-decade reliable burned area
records that provide certainty on fire growth start and end dates based
on satellite hotspot detections
\citep{guindon2014, guindon2020, hall2020}, this paper describes a local
scale (30-m) method for defining a per-pixel proportional carbon stock
change and emissions estimate via a locally calculated fire DM. In this
document, we outline the evidence-based fire DM updated and designed for
a planned, spatially-explicit update to the CBM-CFS3, anchored in a
three severity class paradigm (low, moderate, and high severity). These
fire carbon flux models are built from a blend of aggregated field data
linked to remotely sensed severity, as well as insights from fire
physics and experimental fires. Key knowledge gaps are also highlighted,
with interim solutions presented until further quantification can be
done in field studies, such as from further wildfire observations,
experimental fires, or prescribed fires.

Simplified fire DMs (i.e.~a scalar reduction on 100\% mortality
assumption across all DM components, constant severity across all fires)
have been used in valuable scenario exercises using a spatially-explicit
version of CBM-CFS3 for assessment of future fire and harvest scenarios
\citep{smyth2022}. Here, we provide a data-driven and
regionally-adjusted framework that better reflects the ecological
nuances of moderate and low-severity fire across Canada's diverse
ecozones. This paper describes the technical development of a fire
severity module for the CBM-CFS3 model, version 1.2, benchmarked against
the existing fire approach in the NIR and against independent C
emissions observation during Canada's record fire season in 2023.

\section{Methods}

\subsection{Carbon modelling}

\subsubsection{CBM-CFS3 spatial units}

\begin{figure}
\includegraphics[width=0.75\linewidth]{../RU_plot} \caption{\label{fig::Fig1-RU-ecozones}Reconciliation Units used in the CBM-CFS3 framework.}\label{fig:Fig1-RU-ecozones}
\end{figure}

Carbon reporting in Canada's forests is broken down by Reconciliation
Unit (RU), which is the intersection of terrestrial ecozones and
provincial/territorial boundaries, as shown in Figure
\ref{fig:Fig1-RU-ecozones}. Forest carbon stocks in Canada are
influenced by species composition, age class distribution, natural
disturbance history, human-influenced management regime and climatic
variables, among other factors, which are well-represented by the RU
framework supporting Canada's NIR. Due to the current spatial
imprecision of certain key model data (e.g.~deforestation rates),
analysis finer than the RU-level tends to misrepresent
regional-variation in emission estimates.

\subsubsection{Carbon pool description}

\begin{table}
\centering
\caption{\label{tab:CBM-pools-simple-table}Key components of the CBM-CFS3 model relevant to summary fire behaviour and fuel consumption characteristics from the fire behaviour and fire ecology literature.}
\centering
\begin{tabular}[t]{>{\centering\arraybackslash}p{3cm}|>{\centering\arraybackslash}p{6cm}|>{\centering\arraybackslash}p{3cm}}
\hline
Component & Fire Behaviour & CBM-CFS3 Pool\\
\hline
Stemwood & The main stem of the tree can either survive or be killed and converted to a snag, depending on severity. & Merchantable\\
\hline
Foliage & Susceptible to combustion at high severity and mortality at all severities. & Foliage\\
\hline
Branches & Smaller diameter classes <0.5 cm susceptible to combustion at high severity and mortality at all severities. & Other\\
\hline
Coarse woody debris & Susceptible to combustion at all severities. After fire, uncombusted snags fall down into this pool. & Medium DOM\\
\hline
Forest Floor & Combustion fraction dependent on drought condition; lower susceptibility in Fibric, Humic, and Organic soil horizons (i.e. Slow pool). After fire at any severity, uncombusted foliage and dead branches transfer to these pools. Uncombusted roots can be transferred into these pools for high severity fires when the main stem experiences mortality. & Above Ground Very Fast (Litter); Above Ground Fast (dead fallen branches and coarse roots); Above Ground Slow DOM (F,H,O)\\
\hline
Snags & Higher combustion susceptibility at higher severity & Stem, Branch Snag\\
\hline
\end{tabular}
\end{table}

The carbon pools represented in CBM-CFS3 can be broadly categorized as
live biomass, dead organic matter (DOM) and are described in detail in
\citet{kurzCBMCFS3ModelCarbondynamics2009}. Key components that interact
most with wildfire are summarized in Table
\ref{tab:CBM-pools-simple-table}. Though designed for forest GHG
reporting, the pool structure of CBM-CFS3 does distinguish between
softwood (conifer) and hardwood (broadleaf) that also have large
contrasts in both foliage flammability
\citep{alexanderSurfaceFireSpread2010} and ability to survive low to
moderate intensity surface fires \citep{heonResistanceBorealForest2014}.
Tree biomass pools are further divided into merchantable tree biomass
pools (foliage, stemwood, branches), with separate hardwood and softwood
pools for smaller, subcanopy trees. Representative pool values (in t
C/ha) per RU are produced and updated annually based on updated forest
inventory and disturbance data. Pool size information by RU is provided
in Table SI-1. Upon the detection of a forest disturbance such as fire,
pool C biomass (both dead and alive) can be transferred to other pools
or the atmosphere (or remaining in the same pool) at proportions
prescribed by a DM. Any live or dead biomass pools combusted immediately
are tallied in the direct emissions sums reported here. Live biomass
that is killed but not combusted by the fire is tracked, but experiences
delayed decomposition on the order of years to decades, and therefore is
not tallied within the direct emissions modelling shown below. See
Appendix A for DM examples.

\subsubsection{Definitions and assumptions of forest carbon budget after
fire}

To simplify the process of creating DMs as a distillation of the
complexities of fire severity and combustion patterns, the following
statements are proposed and maintained throughout:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Disturbance matrices are to be in terms of mortality, not survival.
  Mortality here is defined as tree death by the end of the calendar
  year of the fire's occurrence. Tree mortality in subsequent years is
  not modelled here.
\item
  Crown Fraction Burned (CFB) is a mass-based estimate of the portion of
  foliage consumed in the flaming passage of a fire, and is inclusive of
  merchantable and submerchantable trees, both broadleaf and needleleaf.
  Needles that are heat-killed but otherwise not consumed in the fire
  are not considered part of CFB, and are instead considered part of the
  foliage to litter biomass transfer.
\item
  The heat-killed but unconsumed fraction of the canopy is equal to
  (mortality minus CFB).
\item
  In submerchantable trees, mortality is equal to CFB.
\item
  In merchantable trees, CFB is less than or equal to mortality.
\item
  Snags are inclusive of both those killed by prior fire as well as
  those killed by all other causes.
\end{enumerate}

Of these, Crown Fraction Burned (CFB) is an important concept used
primarily in fire behaviour science but not carbon accounting nor fire
ecology. CFB was introduced in the 1992 Fire Behaviour Prediction System
documentation \citep{forestrycanadafiredangerratinggroup1992}, and
provides a simple continuous 0-100 variable for only the consumption of
foliage (which we assume here is inclusive of both conifer and
broadleaf). For our purposes, CFB is the desirable metric as opposed to
ordinal and less precise systems like Canopy Fire Severity Index
\citep{kasischke2000} that allows the user to specify which pools of
canopy biomass are consumed, but not the precise fraction of each given
pool that is consumed.

\subsubsection{Combustion gas emission ratios}

Certain variables, like the partitioning of
CO\textsubscript{2}:CH\textsubscript{4}:CO gas emissions, are constant
throughout ecozones, but vary by flaming vs smouldering combustion
modes. The precise emissions ratios vary slightly between models and
field studies, but for this initial algorithm assessment, we define
these emissions ratios as being identical to those used in Canada's
operational wildfire smoke forecasting system, FireWork
\citep{chen2019}. Emissions ratios are provided in Table
\ref{tab:tab-globalVarsEmissions}.

\begin{table}
\centering
\caption{\label{tab:tab-globalVarsEmissions}Emissions factors for flaming and smouldering used in this model.  Values are the molar fraction of carbon in the unburned biomass and the emitted species, e.g. 87 percent of C in biomass is converted to C as CO2 in flaming combustion.}
\centering
\begin{tabular}[t]{l|r|r}
\hline
Spp & Flaming & Smouldering\\
\hline
CO2 & 0.868 & 0.703\\
\hline
CO & 0.070 & 0.161\\
\hline
PM10 & 0.022 & 0.048\\
\hline
NMOG & 0.016 & 0.035\\
\hline
PM25 & 0.019 & 0.040\\
\hline
CH4 & 0.005 & 0.013\\
\hline
BC & 0.000 & 0.000\\
\hline
\end{tabular}
\end{table}

CO\textsubscript{2} is responsible for 86.8\% of emissions in the
flaming phase, but only 70.3\% of emissions in the smouldering phase,
with a doubling of CO emissions and tripling of CH\textsubscript{4}
emissions (Table \ref{tab:tab-globalVarsEmissions}). With a Global
Warming Potential of CO equal to 1.0 and CH\textsubscript{4} of 28, the
Global Warming Potential per unit of biomass consumption in the
smouldering phase is 1.08 times higher in global warming potential
compared to flaming, not including differential aerosol production and
injection heights, however. With flaming and smouldering each
contributing roughly equally to wildfire emissions, these distinct
flaming and smouldering emissions ratios correspond well to prior
emissions factors used in CBM-CFS3. Note that as currently described,
the sum of CO\textsubscript{2}, CH\textsubscript{4}, and CO emissions
from wildfires only represent approximately 95\% of the fire carbon mass
emitted to the atmosphere, with 0.5--2.0\% of biomass emitted as
particulate matter (e.g.~PM\textsubscript{2.5}, but also
PM\textsubscript{1} and PM\textsubscript{10} classes of particulates at
1 and 10 um diameters, respectively), and an additional 3\%
\citep{hayden2022} to as little as 1\% \citep{simon2010} composed of
non-methane organic gases that have a large range in global warming
potentials as compared to CH\textsubscript{4}.

\subsubsection{Ground plot and remotely sensed fire severity data}

While remotely sensed fire severity metrics are capable of determining
if a specific location falls within a low, moderate, or high severity
fire area \citep{hall2008}, remotely sensed fire severity metrics alone
do not inform estimates of fuel consumption down to specific biomass
pools. Instead, this approach uses the change in biomass pools as
empirically related to per-pixel satellite spectral reflectance indices
(i.e.~dNBR, RBR), using detailed and semi-standardized methods of burn
severity ground plots with unburned controls
\citep[e.g.][]{cockeComparisonBurnSeverity2005, hall2008}. Burn severity
ground plot measurements are often aggregated into a single ``Composite
Burn Index'' (CBI) with a weighting scheme originating in southwestern
U.S. forests
\citep{keyLandscapeAssessment2006, parksGivingEcologicalMeaning2019},
which are classed into low, moderate, and high severity categories. Plot
level measurements of individual forest biomass pools (e.g.~conifer
overstory mortality or canopy consumption) are recorded as part of the
CBI methodology.

In this framework we do not use the CBI aggregated metric itself to
infer biomass consumption, but rather compilations of burn severity
ground plot measurements that include all the individual biomass pool
measurements. Field studies with data describing biomass consumption
fractions for individual biomass pools were available from the
northwestern boreal forest of Canada \citep{french2020, whitman2018}.
Smaller datasets with eastern Canadian and Alaska data were also
available \citep{parksGivingEcologicalMeaning2019}, as were data from
the northwestern conterminous United States in ecozones that overlap
with Canadian forests \citep{saberi2022}. Detailed mortality and surface
consumption data were not available for the Atlantic Maritime and
Mixedwood Plains ecozones, so an estimate was made by subsetting data
from \citet{saberi2022} to a moderate basal area range (25-50
m\textsuperscript{2}/ha) mature eastern mixedwood and conifer-dominated
stands. For the Boreal Cordillera ecozone, data were similarly subset to
only sites with stand heights \textless15 m. Field data for large
diameter mature hardwood trees was only available from
\citet{whitman2018} (primarily aspen, \emph{Populus tremuloides}), and
are used in all other ecozones without modification.

Individual burn severity plots were assigned a severity class based on
ground observations, and an ecozone-level median biomass pool
consumption fraction was computed for each severity class for each
biomass pool. For ecozones without ground plot measurements, an adjacent
and ecologically similar ecozone with observations was used. As such,
Boreal Plains observations were used in the Prairies, Boreal Shield, and
Hudson Plains Ecozones. Similarly, Taiga Shield West observations were
used in the Taiga Shield East. The field survey data on biomass
combustion and mortality rates as stratified by severity class, forms an
improved data-driven and ecologically-informed approach to direct C
emissions estimations from fire termed FireDMs (Fire Disturbance
Matrix-severity).

\subsection{Biomass consumption specifics}

\subsubsection{Overstory tree mortality and consumption}

\begin{table}
\centering
\caption{\label{tab:tab-MortByEcozone}Softwood fractional mortality by ecozone, as derived from median values from field studies in BP, TSW, MC, and PM ecozones.  See Section 2.1.5 for details.}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.45 & 0.81 & 1.00\\
\hline
TP & 0.45 & 0.81 & 1.00\\
\hline
TSW & 0.10 & 0.81 & 1.00\\
\hline
BP & 0.45 & 0.81 & 1.00\\
\hline
BC & 0.24 & 0.65 & 0.98\\
\hline
BSE & 0.45 & 0.81 & 1.00\\
\hline
TSE & 0.10 & 0.81 & 1.00\\
\hline
MC & 0.28 & 0.74 & 0.98\\
\hline
HP & 0.45 & 0.81 & 1.00\\
\hline
TC & 0.24 & 0.65 & 0.98\\
\hline
PM & 0.13 & 0.38 & 0.97\\
\hline
AM & 0.28 & 0.34 & 0.95\\
\hline
MP & 0.28 & 0.34 & 0.95\\
\hline
P & 0.45 & 0.81 & 1.00\\
\hline
\end{tabular}
\end{table}

Numerous process-driven \citep{michaletz2006} or empirical
\citep{hood2017} tree mortality models are available that show
significant skill in predicting tree mortality based on fire behaviour
(i.e.~flame length, rate of spread). Since the driving data in this
model is the mapped fire severity over the landscape scale, fire
behaviour metrics such as flame length or scorching height of bark are
not available as a continuous mapped product. Instead, softwood and
hardwood overstory mortality is calculated per ecozone as a function of
satellite-observed fire severity using the aggregated ground plot data
(Table \ref{tab:tab-MortByEcozone}).

And since large-diameter, live trees killed by fire do not experience
significant live stemwood consumption \citep{talucci2024}, the entirety
of the live stemwood biomass pool that is killed is transferred to the
snag pool. Note that the field data and disturbance modelling undertaken
here only accounts for tree mortality within the calendar year of the
fire, and delayed mortality of over one year has been documented in
boreal low and moderate severity fires \citep{angers2011} where less
than half of total mortality occurs after the year of the fire. Thus,
the modelling here does not account for delayed mortality that may
extend upwards of 5 years after fire.

Crown Fraction Burned (CFB) speaks to the fraction of the live canopy
that is itself consumed in the flaming front. The alternate outcomes
being survival of the foliage, or the mortality of the tree without
canopy consumption, resulting in the dropping of foliage onto the forest
floor. From the definitions stated earlier, the CFB must be lower than
or equal to the mortality rate. Using field studies that show any
partial crown consumption is likely sufficient to result in high rates
if not complete mortality \citep{hood2017}, which is the case in
Canadian trees, which are primarily species with thin bark. Due to the
structure of CBM-CFS3, all high severity fires have their mortality in
the merchantable and smaller trees set to exactly 1.0, which is no more
than a 5\% variance from observed values. Ecozone-specific CFB values
from field studies of burn severity are summarized in Table
\ref{tab:tab-CFBByEcozone}.

\begin{table}
\centering
\caption{\label{tab:tab-CFBByEcozone}Softwood crown fraction burned by ecozone, as derived from median values from field studies in each ecozone.}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.0 & 0.81 & 1.00\\
\hline
TP & 0.0 & 0.81 & 1.00\\
\hline
TSW & 0.1 & 0.81 & 1.00\\
\hline
BP & 0.0 & 0.81 & 1.00\\
\hline
BC & 0.0 & 0.65 & 0.98\\
\hline
BSE & 0.0 & 0.81 & 1.00\\
\hline
TSE & 0.1 & 0.81 & 1.00\\
\hline
MC & 0.0 & 0.74 & 1.00\\
\hline
HP & 0.0 & 0.81 & 1.00\\
\hline
TC & 0.0 & 0.65 & 1.00\\
\hline
PM & 0.0 & 0.38 & 0.97\\
\hline
AM & 0.0 & 0.34 & 0.95\\
\hline
MP & 0.0 & 0.34 & 0.95\\
\hline
P & 0.0 & 0.81 & 1.00\\
\hline
\end{tabular}
\end{table}

The consumption of live bark biomass is calculated in FireDMs, and
consumption rates can be defined by severity class. At the moment,
lacking robust field data on bark biomass consumption rates across
ecozones and severity classes (which are a small portion of the overall
biomass), the bark proportional consumption rate is set to 34\% of the
overstory mortality rate \citep{santín2015}.

\begin{table}
\centering
\caption{\label{tab:tab-ReSproutByEcozone}Ecozone-level average fraction of hardwood overstory species that do not suffer extensive belowground biomass mortality after fire.}
\centering
\begin{tabular}[t]{l|r}
\hline
Ecozone & Resprout Fraction\\
\hline
BSW & 0.75\\
\hline
TP & 0.75\\
\hline
TSW & 0.94\\
\hline
BP & 0.99\\
\hline
BC & 0.76\\
\hline
BSE & 0.67\\
\hline
TSE & 0.78\\
\hline
MC & 0.97\\
\hline
HP & 0.80\\
\hline
TC & 0.27\\
\hline
PM & 0.39\\
\hline
AM & 0.76\\
\hline
MP & 0.32\\
\hline
P & 0.99\\
\hline
\end{tabular}
\end{table}

A major distinction is made between softwood and hardwood trees, where
in Canada's boreal forests, a large fraction of hardwood trees (see
Appendix B) are able to resprout even when the main stem has been killed
by an intense forest fire \citep{brown1987}. Accordingly, the root
mortality rates differ greatly between softwoods and hardwoods, with
softwood root mortality equal precisely to stem mortality, while in
resprouting hardwoods, little root mortality is observed even after
intense fire \citep{pérez-izquierdo2019}. Though spatially explicit
versions of CBM-CFS3 can resolve a species list down to the pixel level,
currently an ecozone-level regional average composition of hardwood
species with resprouting traits (``ReSproutFactor'') is used and is
shown in Table \ref{tab:tab-ReSproutByEcozone}.

The fraction of fine roots contained within the combustible forest floor
layers (the variable ``Prop.Fine.Root.duff'' in the model ) can be a
close to or exceeding 50\% of the fine root biomass \citep{strong1985};
this fine root live biomass is assumed to burn alongside the organic
soils, \citep{benscoter2011}. Fine root allocation is between the
organic soil (termed ``aboveground'' or AG in CBM-CFS3 vs
``belowground'' or BG for mineral soils) is a parameter that can be
ecozone level and is distinct for hardwoods (HW) vs softwoods (SW). As a
result, the calculation for softwood fine root consumption and stemwood
mortality rate (HW.Mort, as observed from field plots) are as follows,
using hardwood as an example:

\begin{equation}
HWFineRootConsump = HW.Prop.Fine.Root.duff \times Duff.Consump.Fract
\end{equation} \begin{equation}
HWFineRootMort.AG = HW.Mort \times HW.Prop.Fine.Root.duff \times (1-Duff.Consump.Fract) \times (1-ReSproutFactor)
\end{equation} \begin{equation}
HWFineRootMort.BG = HW.Mort \times (1-HW.Prop.Fine.Root.duff) \times (1-ReSproutFactor)
\end{equation}

In contrast, the larger diameter of the coarse root biomass pool
prevents its consumption during any smouldering of the duff layer, and
the mortality rate of coarse roots is simply proportional to that of the
stemwood overall.

\subsubsection{Understory tree mortality and consumption}

Understory (or small diameter overstory) tree mortality is defined
separately in the model in the ``submerchantable'' pool, but given the
lack of data on diameter classes in the severity data, robust field data
on differing mortality rates of smaller diameter trees is not available,
and so the understory tree mortality rate is set equal to the overstory
rate as defined in \ref{tab:tab-MortByEcozone} above. Note that smaller
trees with a top height less than 1.4 m are not considered in this pool,
and instead are lumped into the ``other'' pool.

\subsubsection{Litter layer area-wise consumption by severity class}

\begin{table}
\centering
\caption{\label{tab:tab-UnBurnedForestFloorByEcozone}Unburned litter area by ecozone and severity class.  The majority of the data comes from studies in the Boreal Plains and Boreal Shield West, and so values are extrapolated from those two well-observed ecozones to all others.  Ecozones are sorted in order from highest to lowest average annual burned area.}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.20 & 0.08 & 0.05\\
\hline
TP & 0.14 & 0.16 & 0.03\\
\hline
TSW & 0.20 & 0.08 & 0.05\\
\hline
BP & 0.14 & 0.06 & 0.02\\
\hline
BC & 0.14 & 0.06 & 0.02\\
\hline
BSE & 0.20 & 0.08 & 0.05\\
\hline
TSE & 0.20 & 0.08 & 0.05\\
\hline
MC & 0.14 & 0.06 & 0.02\\
\hline
HP & 0.20 & 0.08 & 0.05\\
\hline
TC & 0.14 & 0.06 & 0.02\\
\hline
PM & 0.14 & 0.06 & 0.02\\
\hline
AM & 0.14 & 0.06 & 0.02\\
\hline
MP & 0.14 & 0.06 & 0.02\\
\hline
P & 0.14 & 0.06 & 0.02\\
\hline
\end{tabular}
\end{table}

The litter layer forms the first biomass pool in which a spreading fire
consumes fuel. In low-severity fires, the litter layer is consumed, but
underlying duff material and live trees largely remain
intact\citep{hessburg2019}. In these low-severity patches, some areas of
fully unburned forest floor is present, and is summarized from CBI plot
data by severity class and ecozone in Table
\ref{tab:tab-UnBurnedForestFloorByEcozone}. Logically, since litter
consumption is largely required for the ignition of the underlying duff
layer, this unburned litter areas informs and constrains duff
consumption.

\subsubsection{Snag and stump consumption}

Dead standing trees and branches on average is a biomass pool smaller in
size compared to organic soils in much of Canada's forest, but in areas
of extensive insect-killed trees, recent fires, and blowdown, can be a
substantial biomass pool. Compared to live stemwood of the same
diameter, the low moisture content of snags and snag branches allows for
much greater consumption during the passage of an intense flaming front
\citep{stocks2004}. The snag branch pool experiences almost complete
combustion in high severity fires \citep{talucci2019}, and is highly
correlated with CFB \citep{degroot2022}. The largest dead wood pool is
the standing dead stemwood pool, which remains at most approximately
50\% consumed; the consumption of standing snags pool is not quantified
precisely in the severity plot data available. In the absence of
extensive field data, snag consumption is estimated as:

\begin{equation}
Snag Consumption fraction = \left( 0.5 \times Crown Fraction Burned \right) + 0.05
\end{equation}

And for snag branches, field observations
\citep{talucci2019, degroot2022} reliably point to a higher rate of
consumption for this smaller diameter dead biomass pool:

\begin{equation}
Snag Branch Consumption = \left( 0.9 \times Crown Fraction Burned \right)
\end{equation}

Stumps are tracked as part of the ``Other'' pool in CBM-CFS3. As they
are typically in contact with the upper forest floor, they are assumed
to be consumed at the same rate as coarse woody debris.

\begin{table}
\centering
\caption{\label{tab:tab-CWDByEcozone}Coarse Woody debris consumption rates from pre/post measurements in experimental fires}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.024 & 0.163 & 0.140\\
\hline
TP & 0.000 & 0.218 & 0.238\\
\hline
TSW & 0.000 & 0.218 & 0.238\\
\hline
BP & 0.359 & 0.509 & 0.412\\
\hline
BC & 0.024 & 0.163 & 0.140\\
\hline
BSE & 0.080 & 0.131 & 0.182\\
\hline
TSE & 0.080 & 0.131 & 0.182\\
\hline
MC & 0.024 & 0.163 & 0.140\\
\hline
HP & 0.080 & 0.131 & 0.182\\
\hline
TC & 0.024 & 0.163 & 0.140\\
\hline
PM & 0.024 & 0.163 & 0.140\\
\hline
AM & 0.080 & 0.131 & 0.182\\
\hline
MP & 0.080 & 0.131 & 0.182\\
\hline
P & 0.359 & 0.509 & 0.412\\
\hline
\end{tabular}
\end{table}

\subsubsection{Woody debris consumption}

Limited data is available on the fraction of woody debris consumption
alongside fire severity measurements from wildfires. Coarse woody debris
of overstory stems that makes up 60--80\% of woody debris biomass in
Canada's boreal and temperate forests \citep{hanes2021}, with its
moisture and consumption patterns largely follows the moisture regime of
the Drought Code \citep{mcalpine1995}. In this modelling framework, the
proportion of coarse (\textgreater7.5 cm diameter) and medium
(\textgreater0.5 cm and \textless7.5 cm) woody debris consumption is
estimated based on detailed measurements of consumption from
experimental fires. Coarse woody debris (CWD) is responsible for
approximately 50--75\% of the total woody debris load in most ecozones,
and approximately 60\% of the total woody debris consumption.
Ecozone-level CWD consumption rates are summarized in Table
\ref{tab:tab-CWDByEcozone}.

Note that where historical burn severity data from experimental fires is
not available, the fire recorded fire classification type of surface,
intermittent crowning, and active crown fire are used instead as proxies
for low, moderate, and high severity fire, respectively. Fine woody
debris \textless0.5 cm in diameter is consumed at the exact same rate as
the litter pool (see section above).

\subsubsection{Forest floor consumption}

Unlike canopy consumption metrics that are reliably estimated via burn
severity remote sensing, the depth and magnitude of consumption in the
forest floor is only weakly related to burn severity metrics, since
increasing burn depth in organic soils typically yields little spectral
response in remote sensing imagery
\citep{frenchQuantifyingSurfaceSeverity2020}. Furthermore, there is at
times a temporal disconnect between consumption in the canopy and the
forest floor, with lower-intensity surface fires with a flaming
residence time of a minute or less
\citep{wottonFlameTemperatureResidence2011} without canopy involvement
at times leading to deep smouldering occurring over hours to days
afterwards
\citep{hudaStudyFuelSmokeDynamics2020, huangDownwardSpreadSmouldering2017}.
Consumption of fine fuels in the litter layer of the forest floor is
nearly complete for any given surface fire intensity
\citep{vanwagnerDuffConsumptionFire1972}, consumption of deeper organic
soil horizons (F+H layers in upland forests and upper peat layers in
wetlands) is more dependent on the interaction between moisture content
of the soil organic layer and depth of the organic soil
\citep{forestrycanadafiredangerratinggroup1992, daviesVegetationStructureFire2016}.
While the moisture content of the soil organic layer is not directly
observable nor parameterized in Numerical Weather Model
\citep{hanesEvaluationNewMethods2023}, it is well-estimated simple water
balance models within the Canadian Fire Weather Index System
\citep{vanwagnerDevelopmentStructureCanadian1987} the Drought Code and
Duff Moisture Code, as well as their composite, the Buildup Index. Given
this lack of direct observability of forest floor consumption, this
model uses fire weather and fuel loading as inputs to the forest floor
consumption model, without consideration of the remotely sensed fire
severity observations used in canopy consumption modelling.

In the fire literature in Canada, the soil organic layer is sometimes
termed the Forest Floor Fuel Load (\emph{FFFL}) \citep{letang2012} and
is dominated by the equivalent organic soil Slow pool (Aboveground Slow
Dead Organic Matter, or AGSlowDOM) in CBM-CFS3. Historically, attention
has been paid to the absolute value of Forest Floor Fuel Consumption
(\emph{FFFC})
\citep{forestrycanadafiredangerratinggroup1992, degroot2009}; however in
the case of carbon modelling, it is the relative fraction of consumption
(\emph{FFFC/FFFL}) that is of interest. Given the strong empirical
evidence that the amount of organic soil present strongly influences the
absolute and relative combustion rates
\citep{walkerFuelAvailabilityNot2020}, modelling of forest floor
consumption was conducted on field measurements of the relative fraction
of organic soil consumption. In this scheme, we utilize a composite of
wildfire data from \citep{degroot2009} alongside the ABoVE duff
consumption data \citep{walker2020}, with an alternative modelling
approach to compute the relative amount of consumption (scalar from 0 to
1) rather than directly modelling an absolute value in kg
m\textsuperscript{-2} or cm as otherwise done in the literature. A logit
transform is used on the scalar data to make it suitable for the fitted
non-linear least-squares modelling:

\begin{equation}
logit \left( \frac{FFFC}{FFFL}\right) = [3.91(1 - e^{(-0.008BUI)})] + (-0.53log_{e}(AGSlow))
\end{equation}

where BUI is the Fire Weather Index System's Buildup Index, and AGSlow
in the CBM-CFS3 (given in Mg C/ha in this equation), and also synonymous
with the the Forest Floor Fuel Load (with ecozone averages given in
\citep{letang2012} or site-level data where observed). Assuming an
average carbon content of 50\%, CBM-CFS3 values in Mg C/ha are converted
to fire behaviour units of kg of biomass per squared metre by dividing
by 5.

\begin{table}
\centering
\caption{\label{tab:tab-DuffConsumpTable}Example fire weather, fuel loading, and duff consumption values per ecozone. Note that FFFL values are from the soil-specific Letang et al., (2012) compilation and not directly from the RU values provided in the National GHG Inventory Report.Median Buildup Index of burning is from Barber et al. (2024)}
\centering
\begin{tabular}[t]{l|l|l|l|l}
\hline
Ecozone & Median Buildup Index of Burning & Median FFFL kg m-2 & FFFC kg m-2 & Proportion consumed\\
\hline
BSW & 58 & 6.9 & 2.7 & 0.39\\
\hline
TP & 79 & 12 & 5 & 0.42\\
\hline
TSW & 72 & 1.8 & 1.1 & 0.64\\
\hline
BP & 67 & 7.2 & 3.1 & 0.43\\
\hline
BC & 60 & 7.7 & 3 & 0.39\\
\hline
BSE & 40 & 9.4 & 2.6 & 0.27\\
\hline
TSE & 35 & 5 & 1.6 & 0.32\\
\hline
MC & 112 & 4.3 & 2.9 & 0.67\\
\hline
HP & 52 & 6.1 & 2.3 & 0.38\\
\hline
TC & 59 & 7.8 & 3 & 0.38\\
\hline
PM & 60 & 13.6 & 4.3 & 0.32\\
\hline
AM & 39 & 6.3 & 2 & 0.31\\
\hline
MP & 40 & 9.4 & 2.6 & 0.27\\
\hline
P & 54 & 7.2 & 2.7 & 0.37\\
\hline
\end{tabular}
\end{table}

While ultimately this scheme can be used on individual fires with
estimated or measured fuel loading and specific BUI values, as an
example, an ecozone-averaged fuel load and a multi-year average of BUI
during active fire satellite detection can also be used to provide
representative values to showcase the model framework. Specifically, a
median BUI of detected fire hotspots in Canada from 2003-2021
\citep{barber2024} using the same data as the Canadian CFEEPS-FireWork
wildfire air quality model of \citep{chen2019} is presented in Table
\ref{tab:tab-DuffConsumpTable}, along with proportional consumption
values of the forest floor by ecozone.

Note that the maximum upland Forest Floor Fuel Load is approximately 30
kg m\textsuperscript{-2} (150 Mg C ha\textsuperscript{-1})
\citep{letang2012}; higher values are typically seen only in peat
ecosystems, where the above scheme is still valid, as approximately 33\%
of the data used to fit this model is for organic soil pool values over
30 kg m\textsuperscript{-2} (\textgreater150 Mg Mg C
ha\textsuperscript{-1}). Fully 10\% of the data used in the FFFC model
is for sites with over 60 kg m\textsuperscript{-2} of organic soil.
Absolute consumption values are similar between deep forest floor
organic layers and peatlands \citep{walker2020}, though relative
consumption rates decline rapidly in deeper organic soil layers, as
demonstrated in the model selected here. For Canadian peatlands, the
CaMP model \citep{bona2020} is instead used in spatially explicit
version of CBM-CFS3. Within CaMP, a separate peatland water model driven
by Drought Code determines the thickness of the unsaturated peat layer,
and an amount approximating 12\% of the thickness of the unsaturated
peat is consumed as smouldering consumption. The peat-specific carbon
pools and fire disturbance matrices are fully described in
\citep{bona2020}; large peatland trees will still utilize the DM scheme
described below. Since deeper forest organic soil and peat layers show
approximately similar absolute consumption rates, for the purpose of
this general model description no peatland-specific components of the
fire DMs are required.

\subsection{Source data for emissions comparisons}

Direct wildfire C emissions from the proposed FireDMs scheme in CBM-CFS3
are compared to the FBP System model, which is observed biomass
consumption rates from numerous experimental wildfires across Canada.
The FBP System uses fixed fuel loads per fuel type, while FireDMs uses
regional fuel loads, as represented by biomass pools defined per RU from
forest inventory data.

Since FireDMs also distinguishes flaming vs smouldering combustion, the
Modified Combustion Efficiency is used to compare modelled vs observed
flaming to smouldering ratios:

\begin{equation}
MCE = \frac{CO_{2}}{CO_{2}+CO}
\end{equation}

where an MCE over 0.90 indicates a dominance of smouldering, and an MCE
below 0.85 indicates a dominance of smouldering \citep{akagi2011}. While
MCE is often defined in volumetric gas concentration units (ppmv), in
this study we compute MCE as an output of FireDMs on a molar basis.
Calculations of MCE from FireDMs is compared to localized smoke plume
observations of MCE for distinct periods during the ARCTAS airborne
campaign \citep{hornbrook2011}.

While not strictly a carbon emission from wildfire, N\textsubscript{2}O
is tracked as part of the NIR process and is an important component of
CO\textsubscript{2}-equivalent calculations.
CO\textsubscript{2}-equivalent calculations here will use the CBM-CFS3
emission factor of 0.17 g/kg CO\textsubscript{2} (0.09 g/kg biomass) to
simplify comparisons of C emissions between NIR and FireDMs, recognizing
that this N\textsubscript{2}O emissions factor is lower than widely
cited emissions factors compilations
\citep{binteshahidNEIVAv10NextgenerationEmissions2024, andreaeEmissionTraceGases2019}
between 0.20 and 0.24 g/kg of biomass.

\subsection{Calculation of annual direct C emissions from fire}

In an effort to compare model outputs against an independent,
large-scale set of fire atmospheric emissions, fire direct atmospheric
emissions from the record breaking Canadian 2023 fire season were
computed using the above framework. The classified burn severity product
from the National Burned Area Composite annual production was utilized
(see \citet{hall2020} for an algorithm description). In NBAC, an
internal tracking value ``NFIREID'' is utilized, which is the final
satellite-derived burned area polygon. Fire polygons are split across
any subnational administrative boundaries (i.e.~provinces and
territories). Since carbon pool sizes vary across RU boundaries, this
allows for a single NFIREID to be present across multiple RUs.

A total of 2199 fires as small as 0.09 ha (one 30 by 30 m Landsat pixel)
were mapped in NBAC for burn severity for a total of 14.60 Mha. Only
fires over 100 ha were utilized as a lower limit of where meaningful
per-fire estimates of the fraction of low, moderate, and high severity
burned area was available. Including only fires 100 ha and larger
reduced the total number of fires to 966 but the total area remained
largely the same at 14.58 Mha. A total of 189,704 ha of post-fire
salvage logging was also mapped in 2023 and is assigned to the moderate
severity class after consultation with provincial land managers. The
direct C emissions from fire shown here are not altered by the act of
post-fire salvage logging. Additionally, the NBAC mapping process
accounts for unburned islands (and areas with a mapped fire severity no
different than unburned) which count towards the total fire area but do
not have a disturbance matrix and direct C estimate applied.

All thermal detection hotspots from VIIRS that intersect the NBAC
perimeter were extracted from the historical hotspot archive that
supports the Canadian smoke emissions model CFFEPS-FireWork
\citep{chen2019}, which provide Fire Weather Index values for each
hotspot, including BUI. A unique DM was then calculated for each fire
using the median BUI per fire across all observed hotspots.

To compute total direct fire emissions per fire, a single estimate of
the carbon pool size based on the RU of the centroid of the NBAC polygon
was applied. Fires that cross provincial boundaries are mapped as
discrete fires on either side of the boundary in NBAC, but no such
division of fires was made across ecozone boundaries. While spatially
explicit biomass maps are available for some aboveground components
\citep{guindon2024} and some organic soil components \citep{hanes2022},
the majority of the required pool sizes in CBM-CFS3 for the computation
of the fire DMs are available only at the spatially referenced RU scale.

To calculate the sum total of estimate direct C emission from Canadian
wildfires in 2023, severity maps were created for each fire using 2024
season satellite observations using an approach that produces severity
class maps using both classified spectral indices \citep{whitman2020}
with additional fire environment covariates to predict severity class at
30-m \textbf{\emph{!!!!{[}cite Ellen's upcoming paper{]}!!!}}. A single
representative area-weighted Buildup Index value from fire hotspots was
computed for each fire. A set of DMs (composed of one DM per severity
class) was then applied to Reconciliation Unit carbon stock values for
the total fire area falling into low, moderate, and high severity
classes. The same Buildup Index was used for all severity classes per
fire event when computing the DM per fire event. Per-fire direct C
emissions (i.e.~CO\textsubscript{2}, CO, CH\textsubscript{4},
PM\textsubscript{2.5}, etc.) were then computed and summed by ecozone
and nationally.

RU-level carbon stocks were extracted from the National Forest Carbon
Monitoring Accounting and Reporting System (NFCMARS) CBM-CFS3 model
results for the start of 2023. With the severe drought and extreme fire
weather conditions of the 2023 fire season
\citep{jainDriversImpactsRecordBreaking2024}, patterns of burned area
bias towards older conifer stands found in more typical fire seasons
were instead replaced by unbiased burned area patterns that reflect the
overall landscape composition \citep{boulanger2024}. Thus, the 2023
Canadian fire season provides an ideal case to test regionally-averaged
carbon stock estimates.

\section{Results and Discussion}

\subsection{Direct fire carbon emissions as a function of fire severity
and drought}

\begin{figure}
\includegraphics[width=1\linewidth]{emissions_plot} \caption{\label{fig::non-GWP-total-C-plot}Direct emissions by severity class: solid dark line = high severity, green dot-dash = moderate, blue dashed line = low severity.  Labelled acronyms 
 are RUs named as ecozone then administrative unit, so BC is both Boreal Cordillera 
 and British Columba. Labrador is distinct from the island of Newfoundland for Reconciliation Units,
 so 'Lab' and 'NFLD' is used.  Some small RUs without unique NIR biomass pool data are not shown in this figure but are computed still from adjacent RU from the same ecozone.  Some RU with very small burned area are also not shown in this figure.}\label{fig:non-GWP-total-C-plot}
\end{figure}

Direct fire emissions per hectare by severity class and as a function of
drought condition (BUI) are shown in Figure
\ref{fig:non-GWP-total-C-plot}. Direct fire emissions per hectare were
greatest (using a constant BUI of 200 as a practical upper limit) in the
Pacific Maritime ecozone of British Columbia, with 83 and 71 t C/ha
released in high and moderate severity fires, respectively. This equates
to 295 and 252 t CO\textsubscript{2}-eq/ha and an MCE of 0.90 to 0.89,
respectively. The Pacific Maritime ecozone features some of the highest
relative contributions of canopy fuels to carbon release, with 32\% of
modelled emissions from the canopy, and 68\% from the surface
(i.e.~woody debris, litter, duff, roots etc). Next highest emissions
were 65 t C/ha from high severity fire in the Boreal Shield East (BSE)
of Labrador which features far lower merchantable volume but overall
softwood foliage pools only 5\% smaller than the Pacific Maritime.
Larger aboveground very fast DOM (i.e.~litter) pools in the BSE of
Labrador offset slightly smaller aboveground slow DOM (i.e.~forest floor
duff) pools as compared to the PM.

The lowest emissions per area were estimated to be in the Boreal Shield
West of Saskatchewan, where total emissions of 16 and 22 t C/ha (56 and
76 t CO\textsubscript{2}-eq/ha) for low and moderate severity fire at a
BUI of 200 were 77\% in surface fuels. Despite much lower overall
emissions, these low emissions fires still feature 77--79\% of the total
emissions from surface fuels. The Taiga Shield West of the Northwest
Territories also was modelled to have emissions of only 21.5 t C/ha
under low-severity fire.

Across both low and high severity fires, the effect of drought was
fairly consistent, the emissions from BUI 200 fires (i.e.~very dry
conditions) were higher than those of identical severity class but at a
much lower BUI of 40. This lower BUI of 40 represents the practical
lower limit of large spreading fires in forests in Canada. Variations in
BUI can lead to up to 60\% enhancement in emissions as observed in
Mixedwood Plains of Ontario and Quebec as well as the Atlantic Maritime
of Nova Scotia and Prince Edward Island, but can as small as 10--13\%
enhancement in emissions per hectare in colder northwestern boreal
regions such as the Taiga Shield West of the Northwest Territories, BSW
of Alberta, and Taiga Cordillera of the Northwest Territories. This
patterns is consistent across both high and low severity fire, with the
BUI enhancement of emissions as high as 63\% in low-severity fires,
while the effect is only somewhat smaller in high severity fires at
54\%. Regions with the highest sensitivity to drought, in terms of GHG
emissions, tend to be those with higher softwood (i.e.~broadleaf) forest
composition near 50\% (by volume) or more (i.e.~Atlantic Maritime,
Mixedwood Plains and also Boreal Plains of Manitoba). RUs with the
highest aboveground slow DOM pools also showed similarly high drought
sensitivity of \textasciitilde42\%. RUs with the lowest drought
sensitivity tend to also be the RUs with the lowest overall emissions.

\subsection{Comparison against existing fuel consumption models}

\begin{figure}
\includegraphics[width=0.75\linewidth]{DM_vs_FBP} \caption{\label{fig::fig-DMs-vs-FBP}Fire direct emissions by severity class using the FireDMs approach from this study (lines) as compared to Canadian Fire Behaviour Prediction (FBP) System outputs for Total Fuel Consumption, based on experimental fires of differing fuel types C-2 (boreal spruce), C-3 (Jack and lodgepole pine) as well as M-1 (leafless mixedwood 50\% conifer).  An Initial Spread Index value of 14 is used in all FBP calculations.  Points are colourized by Crown Fraction Burned (CFB).}\label{fig:fig-DMs-vs-FBP}
\end{figure}

The fire disturbance matrix approach is compared to the FBP System in
Figure \ref{fig:fig-DMs-vs-FBP}. The FBP System is used widely in fire
growth modelling as well as in Canada's national air quality model
\citep{chen2019}. The FBP fuel consumption values are based solely on
experimental (i.e.~controlled ignition) fires with fuel consumption
measured within less than an hour of the passage of the flaming front,
and therefore does not include the consumption from long-smouldering
fuel beds such as organic soils and large-diameter woody debris. The FBP
system emphasizes the prediction of fire intensity (i.e.~flame length)
and fire frontal spread rate, with no measurements of the complete fuel
consumption. Fuel consumption values provided by the FBP system are
dependent only on fuel type (related to leading tree species) and BUI,
with no allowance for site-specific variations in fuel load (both canopy
and surface fuel loads are fixed in the FBP). Given the need for safe
experimental fire operations and the demand for firefighting resources,
experimental fires in the FBP with fuel consumption data have a BUI of
no more than 80 for the most common C-2 and C-3 fuels. A BUI of 80
exceeds the area-weighted BUI for most years except in the Montane
Cordillera ecozone (See Supplementary Material Figure SI-1), though the
record-breaking 2023 fire season saw an area-weighted mean BUI for
burning days of 109.

The extrapolation of fuel consumption in the FBP beyond a BUI of 80,
coupled with the lack of long-duration smouldering pools, likely
accounts for the systematic lower estimates of fuel consumption in the
FBP compared to this disturbance matrix approach shown above. For more
southern forests such as the Montane Cordillera, Boreal Plains, or
Boreal Shield East, larger canopy fuels and woody debris volumes likely
contribute to the larger fuel consumption estimates in this approach
compared to the FBP. For the Taiga ecozones, smaller canopy fuel and
woody debris fuel loads as well as thin duff layers (i.e.~AGSlow in the
CBM-CFS3 nomenclature) also contribute to lower total fuel consumption
that falls closer to observed FBP Values.

\subsection{Comparison against observed direct fire emissions}

\subsubsection{\texorpdfstring{Forest fire observations of CO and
CO\textsubscript{2} emissions
ratios}{Forest fire observations of CO and CO2 emissions ratios}}

\begin{table}
\centering\centering
\caption{\label{tab:MCE-from-airborne}Comparison of the Modified Combustion Efficiency (MCE) of airborne gas measurements of Canadian wildfires against modelled MCE}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|l|l|l|l|l|l}
\hline
Study & Date & Subset & Ecozone & Buildup Index & Obs MCE & Modelled MCE\\
\hline
Hornbrook et al 2011 & 2008-07-01 & Afternoon (0.2Low 0.4Mod 0.4High) & Boreal Shield West & 61 & 0.92 & 0.91\\
\hline
Hornbrook et al 2011 & 2008-07-01 & Late Evening (100\% low severity) & Boreal Shield West & 61 & 0.82 & 0.898\\
\hline
Hornbrook et al 2011 & 2008-07-04 & After rain smouldering only low severity & Boreal Shield West & 60 & 0.83 & 0.898\\
\hline
\end{tabular}}
\end{table}

MCE observed by aircraft from \citet{hornbrook2011} during the peak burn
period (when the majority of fuel consumption and area burned occurs)
largely corresponded with modelled values (Table
\ref{tab:MCE-from-airborne}). This suggests the model provides a fair
representation of the balance of flaming and smouldering during large
active wildfires. Subsequent smoke plume observations during periods of
greatly reduced spread and intensity (late evening and after rain)
showed a substantially reduced MCE of 0.82--0.83 that indicates a near
lack of flaming combustion. Even when represented as 100\% low severity
fire in the model, the modelled MCE only declines to 0.90, suggesting
FireDMs does not adequately capture carbon emissions ratios during
marginal smouldering conditions. Since the fire DM model is based on
area burned, fire activity such as smouldering but with minimal actual
area burned increased is going to show an MCE far lower than areas of
low severity fire spread, which are typically still a low sub-canopy
flaming front that features a mix of smouldering duff and woody debris
alongside flaming consumption of litter \citep{mcrae1994, mcrae2017}.
During the same ARCTAS campaign over a larger sample of 39 fires,
\citet{vayPatternsCO2Radiocarbon2011} observed a mean MCE of 0.89 for
smoke plumes within 2 km of a large wildfire.

\subsection{2023 Canadian wildfire season direct emissions}

\begin{figure}
\includegraphics[width=0.75\linewidth]{emissions2023} \caption{\label{fig::Emissions-2023-by-RU}Comparison of CO~2~-e emissions per hectare between the FireDMs estimate and current methodology, the 2025 National Inventory Report for the 2023 wildfires.  Dots are labelled by RU and coloured by ecozone (see Figure 1), with dot size proportional to 2023 area burned.  The solid line is the 1:1 reference line, and the dashed line represents 25\% deviation from a 1:1 relationship.}\label{fig:Emissions-2023-by-RU}
\end{figure}

\begin{landscape}\begin{table}[!h]
\centering
\caption{\label{tab:tab-RU-CO2e-comp}Comparison of per hectare CO2e direct emissions from this study against the 2025 National Inventory Report for the 2023 wildfire season in Canada. Rows are sorted by decreasing 2023 area burned.  Note that for RUs with no managed forest area, the nearest forest inventory data available is used.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}}
\hline
Jurisdiction & Ecozone & Reconciliation Unit & Area Burned (Mha) & Moderate Severity Fraction & High Severity Fraction & This Study Emissions t C/ha & This Study Emissions t CO2-eq/ha & NIR 2025 Emissions tCO2-eq/ha\\
\hline
Lab+QC & taiga shield east & 3+14 & 2.50 & 0.39 & 0.31 & 41.9 & 147.3 & 99\\
\hline
Northwest Territories & taiga plains & 50 & 2.01 & 0.23 & 0.52 & 26.8 & 94.2 & 114\\
\hline
Alberta & boreal plains & 34 & 1.53 & 0.30 & 0.42 & 45.1 & 158.0 & 163\\
\hline
Northwest Territories & taiga shield west & 51 & 1.50 & 0.19 & 0.58 & 22.3 & 78.5 & 129\\
\hline
Quebec & boreal shield east & 15 & 1.38 & 0.39 & 0.27 & 30.3 & 106.5 & 92\\
\hline
British Columbia & taiga plains & 38 & 1.29 & 0.17 & 0.65 & 35.4 & 124.2 & 161\\
\hline
Alberta & taiga plains & 31 & 0.88 & 0.18 & 0.67 & 36.8 & 129.1 & 144\\
\hline
Saskatchewan & boreal shield west & 27 & 0.70 & 0.19 & 0.65 & 19.1 & 67.3 & 83\\
\hline
British Columbia & montane cordillera & 42 & 0.68 & 0.26 & 0.39 & 35.9 & 125.7 & 189\\
\hline
ON+QC+MB & hudson plains & 18+13+25 & 0.47 & 0.23 & 0.42 & 31.7 & 111.5 & 128\\
\hline
Saskatchewan & boreal plains & 28 & 0.31 & 0.22 & 0.41 & 29.3 & 102.9 & 91\\
\hline
AB+MB+SK & taiga shield west & 32+21+26 & 0.28 & 0.23 & 0.60 & 39.7 & 139.3 & 146\\
\hline
Ontario & boreal shield west & 16 & 0.25 & 0.23 & 0.47 & 23.9 & 83.9 & 94\\
\hline
Yukon Territory & taiga cordillera & 45 & 0.20 & 0.16 & 0.49 & 47.6 & 167.2 & 198\\
\hline
British Columbia & boreal cordillera & 40 & 0.14 & 0.12 & 0.56 & 49.4 & 173.6 & 209\\
\hline
Yukon Territory & boreal cordillera & 46 & 0.11 & 0.16 & 0.58 & 50.0 & 175.7 & 179\\
\hline
\end{tabular}}
\end{table}
\end{landscape}

\begin{table}
\centering
\caption{\label{tab:tab-Model-comp-Emissions-2023-table}Comparison of total carbon emissions estimates for the Canadian 2023 fire season.  Note that the Byrne et al 2024 estimate shown here uses the emissions ratio for CO inferred from this study.  See main text for details.}
\centering
\begin{tabular}[t]{c|c|c}
\hline
Source & Approach & TotalEmission\\
\hline
This study & Severity-Inventory & 494\\
\hline
Byrne 2024 & Total column CO anomaly & 510*\\
\hline
CAMS-GFAS & Fire Radiative Power & 478\\
\hline
FireWork & Hotspot-FBP & 168\\
\hline
\end{tabular}
\end{table}

A total of 494 Mt C was estimated to be released directly by fires in
Canada in 2023. The area-weighted mean Buildup Index for all fires in
Canada in 2023 was 109, representing severe but not uniformly
exceptional drought conditions in Canada's northern forests. The
area-weighted mean total C emissions per unit area was 33.87 t C/ha,
though 90\% of the emissions per unit area were between the 5th
percentile of 15 t C/ha typical of the Taiga Plains ecozone under low
drought conditions and the 95th percentile of 54 t C/ha typical of
Pacific coastal forests.

Comparison of emissions totals against the NIR is only possible for
spatial units (i.e.~Reconciliation Units, provinces, or ecozones) where
the entire RU is composed of managed forest. In British Columbia, across
2.2 Mha burned, these FireDMs estimates were consistently lower than
NIR. This was driven by a lower average emissions in FireDMs for both
the Taiga Plains with 1.3 Mha burned (124 t CO\textsubscript{2}-eq/ha)
and Montane Cordillera with 0.68 Mha burned (127 t
CO\textsubscript{2}-eq/ha) as compared to the NIR (161 and 189 t
CO\textsubscript{2}-eq/ha, respectively). For Alberta the 1.5 Mha of
Boreal Plains ecozone burned showed close agreement (155 vs 163) as well
as in the Taiga Plains (130 vs 144). The Taiga Plains fires of both
Alberta and British Columbia were largely adjacent, and the FireDMs
output was very similar (123 vs 129) across nearly identical moderate
and high severity fractions, but the NIR showed a larger contrast (144
vs 161) that may originate from the underlying assumptions of the
previous methods of calculating fire emissions in the NIR.

The RU with the largest burned area in 2023 was in the unmanaged forest
of Quebec's Taiga Shield East, where NIR pool sizes from the adjacent
jurisdiction of Labrador TSE were used in the FireDMs estimates, as no
NIR pool sizes were available for Quebec's TSE ecozone RU, as there is
no managed forest in that RU (the objective of the NIR being to report
on GHG emissions in managed forest). Over this 2.5 Mha of burned area,
the Quebec TSE FireDMs emissions estimates were substantially larger
(149 t CO\textsubscript{2}-eq/ha) compared to NIR (99 t
CO\textsubscript{2}-eq/ha, see Figure \ref{fig:Emissions-2023-by-RU}).
In the Quebec Boreal Shield East ecozone where NIR pools are available,
the FireDMs were still larger than NIR, though the gap between the two
was much smaller (106 vs 92). Only the Manitoba Boreal Plains and Yukon
Taiga Plains showed a similarly larger estimate in the FireDMs compared
to NIR, with all other RUs showing a typically 10--30\% reduction in
emissions in the FireDMs compared to the NIR. Overall, this new
emissions estimate method will yield more representative fire emissions
estimates that are sensitive to annual differences in drought condition
and fire-specific patterns of severity. The small overall impact is
likely due to larger soil organic layer emissions in the FireDMs being
offset by lower canopy consumption in the low and moderate severity
areas.

\citet{byrneCarbonEmissions20232024} used observed total atmospheric
column excess CO and a range of MCE values to estimate total fire C
emissions in Canada in 2023 of between 570-727 Mt C with a mean estimate
of 647 Mt. The uncertainty in the estimate from
\citet{byrneCarbonEmissions20232024} lies primarily in the uncertain
CO\textsubscript{2}:CO ratio (more commonly computed as the normalized
ratio MCE) that was estimated to be between 7.8--10.8 g
CO\textsubscript{2} / g CO. Our bottom-up estimates that partition
flaming vs smouldering shows a lower CO\textsubscript{2}:CO estimate of
6. This lower CO\textsubscript{2}:CO ratio (i.e.~more smouldering) if
applied to the data from \citet{byrneCarbonEmissions20232024} would
reduce their lower range of total C emissions to 505 Mt C, which is
comparable to the 494 Mt C computed from this bottom-up approach.
Estimates of total carbon emissions based solely on the sum of observed
Fire Radiative Power (FRP) from Copernicus-CAMS (GFASv1.2
\citep{kaiserBiomassBurningEmissions2012}) was 478 Mt C
\citep{jonesStateWildfires202320242024}. The operational air quality
model for Canada produces wildfire smoke emissions estimates using the
CFFEPS-FireWork framework \citep{chen2019} which utilizes active fire
satellite detections coupled to biomass burning rates from the Canadian
Forest Fire Danger Rating System which are known to underestimate total
emissions from forest floor combustion \citep{degroot2009}. As a result,
the CFFEPS-FireWork total emissions in 2023 with their exceptional
nation-wide moisture deficits
\citep{jainDriversImpactsRecordBreaking2024} underestimate total
emissions compared to other methods, with CFFEPS estimates of CO
emissions only \textasciitilde40\% of satellite observed values
\citep{griffinBiomassBurningCO2024, voshtaniQuantifyingCOEmissions2025}.
Even after assimilating satellite CO and tower-based total carbon
measurements, CFFEPS still retains 20\% understimating bias, likely
attributable to an estimate of peak CO (i.e.~smouldering) emissions that
are lower than reality \citep{voshtaniQuantifyingCOEmissions2025}.

\subsubsection{Relationship to other estimates}

The forest floor emissions modelling scheme used here builds upon the
CanFIRE model \citep{degroot2013} which incorporates a similar estimate
of absolute forest floor emissions based on fuel type and various Fire
Weather Index inputs (including but not limited to Buildup Index). While
the CanFIRE model is also capable of estimating tree mortality, the
premise of CanFIRE lies in the use of the FBP System to model fire
intensity and a physiological-thermodynamic model of tree damage and
mortality. CanFIRE is able to run entirely in scenario or forecast mode,
i.e.~no fire severity map is needed to run the model, unlike the focus
here on a mechanism to estimate carbon fluxes and pools after fire
severity is mapped. Ultimately, models like CanFIRE can be used for
near-real time emissions estimates of direct and indirect fire carbon
emissions (and also for prescribed fire planning and scenario testing),
while this modelling framework is best used solely operational carbon
accounting and reporting given its strong dependence on severity maps.
While fire severity can be estimated empirically based on geospatial
inputs without observation using multispectral satellite data such as
Landsat, estimation using coupled fire behaviour and ecology models such
as CanFIRE is a more direct approach. Under severe drought conditions
and light winds, very large fires often create more wind and energy than
is available in gradient winds as measured at nearby airports and fire
weather observing stations
\citep{clarkAnalysisSmallScaleConvective1999}. Thus, fire behaviour and
fuel consumption models solely driven by wind inputs from distant
meteorological stations can under-predict fire intensity and therefore
likely fire severity. While fire-atmosphere models are available for
research \citep{coenGenerationForecastExtreme2018} and some forecasting
and planning purposes \citep{linn2020}, modelling resources are
typically not made available for the extensive and largely unsuppressed
fires in northern Canada. Fire severity mapping after the fact is able
to account for high fire severity \citep{whitman2018} even when fire
spread occurs under light winds more associated with lower fire
intensity \citep{whitman2024}.

While the fire DMs presented here are designed for use in NFCMARS for
GHG estimation and reporting, their simplicity and similarity to many
other forest carbon schema allows them to be used elsewhere such as in
other forest dynamics \citep{brecka2020} and earth system models
\citep{melton2020} that require estimates of Canadian forest carbon
emissions from wildfire. \citet{stenzel2019} showed that
severity-informed fire C estimates (with snags) in the US are only
30-40\% as large as fixed or variable severity data using their
LANDIS-type models. Large over-estimates of in-fire bole consumption in
models were not observed to correspond to measurements in the field. In
the model presented here, our estimates of snag consumption are based on
simple but logical relationships with CFB, but more comprehensive data
collection and field observations would be required to extend the
accuracy of the snag consumption scheme.

\subsubsection{Indirect fire emissions}

While fire emissions within the year of the fire are majority of the GHG
flux, enhanced post-fire decomposition of dead biomass persists for many
years after a fire. The increase in post-fire tree mortality between the
year of the fire and the year following the fire is as much as 30\% in
low and moderate-severity stands \citep{angers2011}. This extended
mortality is not captured in year-of fire severity mapping but is likely
better assessed using fire severity data captured the year following
fire, as is operational practice in Canada. Similarly, the transition of
fire-killed stems (snags) from upright to the forest floor woody debris
takes between 5-8 years for 50\% of stems to fall \citep{angers2011}
with stemfall rate highest in low-severity fire. Field observations show
that initial assessments of fire severity are the primary predictors of
snag fall \citep{angers2011} and decomposition \citep{boulanger2011}
rates, meaning the mapped severity method used here provides a useful
input for multi-year fire carbon modelling of the snag pool in CBM-CFS3.
For organic soil pools, fire has been shown to suppress decomposition
rates in upland soil pools where drier post-fire conditions are present
\citep{holden2015}, while in permafrost upland \citep{odonnell2011} and
peatland \citep{gibson2018, gibson2019} systems, fire has profound
impacts on soil carbon pools by rapidly increasing thaw depths and
subsequent decomposition rates. Currently in CBM-CFS3, decomposition
rates are calibrated against field decomposition litterbag experiments
\citep{trofymow2002} and annual climate metrics that do not take into
account how disturbances such as fire (and fire of varying severity)
modify decomposition rates in the absence of a change in climate.

\subsubsection{Model gaps}

Currently, FireDMs only accounts of regionally-averaged soil carbon
stocks, meaning that RUs with high peatland areas will show higher
organic soil slow pool size, but peatlands themselves are not spatially
represented in the model. Instead, peatlands influence the reported
Aboveground Slow pool size. Currently, fire disturbance in peatlands is
performed by the CaMP model, which uses the closely related Drought Code
fire weather metric to estimate peat layer consumption \citep{bona2020}
and uses the overstory carbon schema of CBM-CFS3 to estimate overstory
tree carbon pools and fluxes. Direct satellite monitoring of upland
forest organic soil and peatland carbon loss via burn severity
monitoring is possible but remains a challenge to implement with
accuracy for monitoring purposes \citep{bourgeau-chavez2020}. Despite
the large carbon stock (c.~500 Mg C/ha from
\citet{beilmanPeatCarbonStocks2008}), the mean C emissions per area in
peatland due to fire (65 t C/ha) as modelled by \citet{bona2024} are
comparable to regional emissions from peat-rich ecozones such as the
Boreal and Taiga Plains under moderate to severe drought conditions.
Indeed, it is under these moderate to severe drought conditions that
peatlands burn more frequently \citep{turetsky2004, thompson2019} and
severely \citep{kuntzemann2023}.

While Canadian wildfires shown an overall selection bias towards
preferentially burning older conifer stands \citep{bernier2016}, fuel
selectivity against less flammable portions of the landscape decreases
strongly under severe drought conditions \citep{parks2018}. The severe
drought conditions experienced in Canada in 2023
\citep{jainDriversImpactsRecordBreaking2024} are an ideal setting to
compare an emissions model using spatially referenced biomass data
against observed emissions. The 2023 fires were observed to largely burn
boreal forest ecosystems at the same rate as their abundance on the
landscape, owing to severe drought and fire weather conditions
\citep{boulanger2024}. Emissions model evaluation against individual
fires or in years of less profound drought would be more likely to
highlight the limitation of the regionally-averaged carbon pool
(i.e.~fuel load) values used here. Ultimately, the mapped severity used
here is best paired with mapped carbon pools at a similar scale, such as
the 1-ha forest carbon modelling for analysis and scenario testing used
by \citet{smyth2024}. Future work will extend this fire disturbance
algorithm to finer-scale carbon reporting using gridded data as it
becomes available for annual reporting purposes.

Species-specific traits in trees with overlapping ranges, such as
resprouting in aspen \citep{brown1987} but not other broadleaves such as
oak or maple, are not explicitly handled in this model. Instead, the
relative abundance of trees with contrasting traits that influence
ecological outcomes such as fire survival are lumped at the ecozone
scale from the aggregation of the plot data. While ecozone-level
contrasts in key considerations such as overstory mortality do strongly
vary by ecozone (Table \ref{tab:tab-ReSproutByEcozone}), the same DM
(e.g.~hardwood root mortality) is applied in adjacent stands at the same
severity class despite the potential for strongly contrasting traits
that are readily tied back to mapping at the stand level by leading
species. Alternately, models such as CanFIRE can account for
species-level contrasts in fire ecology traits, but compiling the
relevant ecophysiological properties and traits for all tree species
across the spectrum of fire intensity in Canada remains incomplete at
this time.

\section{Conclusions}

Carbon emissions from wildfires in Canada represent a substantial pulse
input of greenhouse gases to the atmosphere: the 2023 fire emissions in
Canada were an input of approximately 494 Mt C. A modelling framework to
extend the current fire and greenhouse gas reporting in Canada is
presented. In contrast to the existing modelling system that utilizes a
fixed fire severity (i.e.~tree mortality) assumption, a field-calibrated
satellite fire severity mapping process that follows mature and
well-established scientific methods is used. Above-ground carbon pool
changes (from live to dead and in situ as well as to the gas phase) rely
on a robust field observation dataset that relates back to satellite
metrics. Evaluation of the modelling presented above against fully
independent airborne observations of CO:CO\textsubscript{2} emissions
ratios for boreal wildfires indicates the modelling of proportion of
flaming vs smouldering emissions are well-replicated by the model. With
confidence in this modelled CO:CO\textsubscript{2} ratio, the total fire
CO emissions for the 2023 wildfire season in Canada (with a record 15
Mha burned) is broadly consistent with fire season estimates using
satellite total column CO anomalies.

While this prototype carbon flux framework utilizes regionally-averaged
carbon stock estimates, future systems deployment within Canada's carbon
accounting system is likely to incorporate precisely mapped (30 m)
carbon pools alongside the finely mapped fire severity products (30 m)
used here. As both the spatial estimates of carbon stocks across
Canada's forested ecosystems improves alongside additional field
observations, it is anticipated that this modelling framework will
increase in both accuracy and precision over time.

\newpage

\section{Appendix A: Disturbance Matrix Examples}

Note that the pool source is shown in rows, and the destination pool is
shown in the columns.

\begin{landscape}\begin{table}[!h]
\centering
\caption{\label{tab:example-DM-tables}Low severity Disturbance Matrix in BP.  Note: only some biomass and atmospheric pools are shown.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{3cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}}
\hline
  & Softwood Merchantable & Softwood Stem Snag & Medium DOM
 & Softwood Foliage & Aboveground Very Fast DOM & CO2 & CH4 & CO & PM25\\
\hline
Softwood Merchantable & 1 & 0.000 &  &  &  &  &  &  & \\
\hline
Softwood Stem Snag &  & 0.475 & 0.475 &  &  & 0.043 & 0.000 & 0.004 & 0.001\\
\hline
Medium DOM &  &  & 0.551 &  &  & 0.315 & 0.006 & 0.072 & 0.018\\
\hline
Softwood Foliage &  &  &  & 0.55 & 0.45 & 0.000 & 0.000 & 0.000 & 0.000\\
\hline
Aboveground Very Fast DOM &  &  &  &  & 0.14 & 0.746 & 0.004 & 0.060 & 0.016\\
\hline
CO2 &  &  &  &  &  &  &  &  & \\
\hline
CH4 &  &  &  &  &  &  &  &  & \\
\hline
CO &  &  &  &  &  &  &  &  & \\
\hline
PM25 &  &  &  &  &  &  &  &  & \\
\hline
\end{tabular}}
\end{table}
\end{landscape}

\begin{landscape}\begin{table}[!h]
\centering
\caption{\label{tab:example-DM-tables}Mod severity Disturbance Matrix in BP.  Note: only some biomass and atmospheric pools are shown.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{3cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}}
\hline
  & Softwood Merchantable & Softwood Stem Snag & Medium DOM
 & Softwood Foliage & Aboveground Very Fast DOM & CO2 & CH4 & CO & PM25\\
\hline
Softwood Merchantable & 0.19 & 0.81 &  &  &  &  &  &  & \\
\hline
Softwood Stem Snag &  & 0.00 & 0.545 &  &  & 0.395 & 0.002 & 0.032 & 0.009\\
\hline
Medium DOM &  &  & 0.462 &  &  & 0.379 & 0.007 & 0.087 & 0.022\\
\hline
Softwood Foliage &  &  &  & 0.19 & 0.00 & 0.703 & 0.004 & 0.057 & 0.015\\
\hline
Aboveground Very Fast DOM &  &  &  &  & 0.06 & 0.816 & 0.005 & 0.066 & 0.018\\
\hline
CO2 &  &  &  &  &  &  &  &  & \\
\hline
CH4 &  &  &  &  &  &  &  &  & \\
\hline
CO &  &  &  &  &  &  &  &  & \\
\hline
PM25 &  &  &  &  &  &  &  &  & \\
\hline
\end{tabular}}
\end{table}
\end{landscape}

\begin{landscape}\begin{table}[!h]
\centering
\caption{\label{tab:example-DM-tables}High severity Disturbance Matrix in BP.  Note: only some biomass and atmospheric pools are shown.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{3cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}}
\hline
  & Softwood Merchantable & Softwood Stem Snag & Medium DOM
 & Softwood Foliage & Aboveground Very Fast DOM & CO2 & CH4 & CO & PM25\\
\hline
Softwood Merchantable & 0 & 1 &  &  &  &  &  &  & \\
\hline
Softwood Stem Snag &  & 0 & 0.450 &  &  & 0.477 & 0.003 & 0.039 & 0.010\\
\hline
Medium DOM &  &  & 0.576 &  &  & 0.298 & 0.006 & 0.068 & 0.017\\
\hline
Softwood Foliage &  &  &  & 0 & 0.00 & 0.868 & 0.005 & 0.070 & 0.019\\
\hline
Aboveground Very Fast DOM &  &  &  &  & 0.02 & 0.851 & 0.005 & 0.069 & 0.019\\
\hline
CO2 &  &  &  &  &  &  &  &  & \\
\hline
CH4 &  &  &  &  &  &  &  &  & \\
\hline
CO &  &  &  &  &  &  &  &  & \\
\hline
PM25 &  &  &  &  &  &  &  &  & \\
\hline
\end{tabular}}
\end{table}
\end{landscape}

\begin{landscape}\begin{table}[!h]
\centering
\caption{\label{tab:example-DM-tables}High severity Disturbance Matrix in TSW.  Note: only some biomass and atmospheric pools are shown.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{3cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}}
\hline
  & Softwood Merchantable & Softwood Stem Snag & Medium DOM
 & Softwood Foliage & Aboveground Very Fast DOM & CO2 & CH4 & CO & PM25\\
\hline
Softwood Merchantable & 0 & 1 &  &  &  &  &  &  & \\
\hline
Softwood Stem Snag &  & 0 & 0.450 &  &  & 0.477 & 0.003 & 0.039 & 0.010\\
\hline
Medium DOM &  &  & 0.724 &  &  & 0.194 & 0.004 & 0.044 & 0.011\\
\hline
Softwood Foliage &  &  &  & 0 & 0.00 & 0.868 & 0.005 & 0.070 & 0.019\\
\hline
Aboveground Very Fast DOM &  &  &  &  & 0.05 & 0.825 & 0.005 & 0.066 & 0.018\\
\hline
CO2 &  &  &  &  &  &  &  &  & \\
\hline
CH4 &  &  &  &  &  &  &  &  & \\
\hline
CO &  &  &  &  &  &  &  &  & \\
\hline
PM25 &  &  &  &  &  &  &  &  & \\
\hline
\end{tabular}}
\end{table}
\end{landscape}

\newpage

\section{Appendix B: List of Resprouting Hardwoods of Canada}

Alnus spp. Arbutus men. Betula all. Betula pap. Betula pop. Fraxinus
ame. Fraxinus nig. Fraxinus pen. Populus bal. Populus gra. Populus tre.
Populus tri. Quercus spp. Salix spp.

\newpage

\section{Appendix C: Modelling of soil organic layer consumption}

For national annual estimates of forest organic soil layer consumption
during wildfire, implementations that only utilize Canadian experimental
fire data from the Fire Behaviour Prediction System will be limited to a
maximum consumption value of 5 kg (biomass) m\textsuperscript{-2} of
total surface fuel (woody debris, litter, and duff) of 5 kg
m\textsuperscript{-2}, or 25 Mg C ha\textsuperscript{-1}, given the
observation dataset and fitted model parameters. For the common ``C-2''
boreal spruce fuel type for instance, Surface Fuel Consumption, SFC
(biomass units in kg m\textsuperscript{-2} not kg C) is modelled as:

\begin{equation}
SFC = 5.0 \left(1-e^{-0.0115BUI} \right)^{1.0}
\end{equation}

This model form has the distinct advantage of SFC being 0.0 at a BUI of
zero. The model parameters vary by fuel type (i.e.~deciduous broadleaf
fuels are limited to 1.5 kg m\textsuperscript{-2} of maximum SFC) but
are fixed within a fuel type.

More recent observations and modelling from \citet{degroot2009} extended
the FBP data with an additional 128 observations from 7 additional
wildfires, and the ABoVE project compiled over 1,000 field observations
of depth of burn and C stocks before and after wildfire in Canada and
Alaska, over 600 of which are in North American Level II ecoregions also
occurring in Canada \citep{walker2020}. \citet{degroot2009} provides a
concise and informative improvement on the FBP fuel consumption
equations, where both a Fire Weather Index System component (in this
case, Buildup Index) is used similarly to Buildup Index in the FBP, but
importantly, the site-level organic soil layer fuel load is also
accounted for, which allows for the greater absolute combustion in
deeper organic soils that is moderated by the natural logarithm
transformation:

\begin{equation}
log_{e}(FFFC) = -4.252+0.710log_{e}(DC) + 0.671log_{e}(FFFL)
\end{equation}

where FFFC is Forest Floor Fuel Consumption (SFC minus surface woody
debris) in kg (biomass) m\textsuperscript{-2} and FFFL is Forest Floor
Fuel Load in kg m\textsuperscript{-2}. The forest floor as defined here
is inclusive of the litter and duff layers, live mosses and lichens.
This model presented above fits well within the dataset and extends the
observed maximum FFFC to nearly 10 kg m\textsuperscript{-2}. The ABoVE
synthesis of FFFL and FFFC \citep{walker2020} expands upon a slightly
smaller dataset used in a modelling summary also by
\citet{walkerFuelAvailabilityNot2020}, where structural equation
modelling was used to explore drivers of FFFC but no concise and readily
reproducible modelling is produced. The results of the SEM from
\citet{walkerFuelAvailabilityNot2020} emphasized a greater role of FFFL
over DC, though coarse reanalysis that lacked local fire agency weather
stations was used. An analysis of just 2014 fires in the Northwest
Territories by \citet{walkerSoilOrganicLayer2018} showed that while the
mean depth of burn across all black spruce stands was 6--10 cm, the
driest (xeric) black spruce stands with the smallest FFFL showed upwards
of 75\% soil organic consumption, while deeper organic soils in
subhygric black spruce stands showed less than 25\% consumption.

To provide the largest possible dataset for FFFC and FFFL, the ABoVE
synthesis was combined with wildfire data from de Groot et al 2009 not
otherwise found in the ABoVE synthesis. The ABoVE synthesis sites in the
Alaska Boreal Interior ecoregion, which have equivalent Canadian ecozone
were excluded due to the presence of continuous permafrost and deep
organic soils, but Alaska Boreal Cordillera sites near the Yukon border
were utilized. Experimental fire data from the FBP data was not used, as
deeper combustion measurements resulting from hours and days of
smouldering combustion captured in wildfire data are not available in
experimental fires where extensive smouldering is not measured due to
suppression.

For the purposes of improving national estimates of the fractional soil
organic layer loss during wildfire, this framework emphasizes the
proportional C stock loss (as with all CBM-CFS3 disturbance matrices)
rather than the absolute value of combustion. In contrast to the
modelling of absolute combustion value, any analysis of proportions is
best conducted as logit- transformed data, where the logit
transformation is:

\begin{equation}
logit(p) = log \frac{p}{1-p}
\end{equation}

which effectively transforms a data of proportions of {[}0,1{]} to a
Gaussian distribution with a range of approximately -5 to +5 (in this
dataset), and a mode approximately at zero.

In the logit transformed space, saturation-type non-linear curve using
the relevant FWI component was fitted in a non-linear least squares
model, but an additive term of the natural-logarithm transformed forest
floor fuel load (FFFL) (given as AGSlow pool in Mg C/ha) was used as
well. The non-linear least squares model fit was conducted using the
Levenberg-Marquardt nonlinear least-squares algorithm found in MINPACK
\citep{elzhovMinpacklmInterfaceLevenbergMarquardt2023} R package, which
supported bounded parameter constraints.

In the abstract, the model follows the form:

\begin{equation}
logit \left( \frac{depth of burn}{pre-fire organic depth}\right) = [c (1 - e^{(a  BUI)})] + (b log_{e}(AGSlow))
\end{equation}

with fitted parameters as:

\begin{equation}
logit \left( \frac{depth of burn}{pre-fire organic depth}\right) = [3.50 (1 - e^{(-0.008 BUI)})] + (-0.53 log_{e}(AGSlow))
\end{equation}

Note the ``b coefficient on the parameter associated with the forest
floor fuel load (AGSlow) of -0.53, which results in larger organic layer
fuel loads leading to smaller proportional consumption values, which
follows the patterns shown by \citet{walkerCrossscaleControlsCarbon2018}
for NWT fires of 2014.

The a parameter term that forms the exponent of \emph{e} alongside the
Buildup Index is related to the BUI value at which half of the maximum
possible asymptotal consumption value is observed (for a given FFFL
value). The NLS fitting was given a minimum value of -0.008 such that a
50\% consumption rate was modelled as occurring at or around a BUI value
of 70 for typical upland spruce forest floor (FFFL of 8 kg/m2 or AGSlow
of 40 t C/ha) following the wildfire data of \citet{degroot2009} as well
as experimental fire observations in spruce forests from the FBP System.
The other parameters were fit to the best possible value with no
constraint.

For example, using a moderately thick \textasciitilde12 cm thick organic
soil layer, the proportion of consumption as a function of Buildup Index
using the model above:

\begin{figure}
\includegraphics[width=0.75\linewidth]{FFFC_vs_BUI_plot} \caption{Example of the forest floor consumption model for a duff layer (AGSlow) of 60 Mg C ha-1 (12 kg m-2)}\label{fig:example-FFFC-vs-BUI-plot-nls}
\end{figure}

With the parameter constrained NLS fitting, the proportional consumption
model for the forest floor has a leave-one-out (conducted at the
fire-level, not plot) cross validated r\textsuperscript{2} of 0.52 and a
Mean Percent Error of 45\%

\begin{verbatim}
## Scale for y is already present.
## Adding another scale for y, which will replace the existing scale.
## Scale for y is already present.
## Adding another scale for y, which will replace the existing scale.
## Scale for x is already present.
## Adding another scale for x, which will replace the existing scale.
## Saving 6.5 x 4.5 in image
\end{verbatim}

\begin{verbatim}
## Warning: Removed 4 rows containing missing values or values outside the scale range
## (`geom_point()`).
\end{verbatim}

\begin{figure}
\includegraphics[width=0.75\linewidth]{FFFC_biplot} \caption{Leave one out cross-validation of the forest floor consumption model.  Where multiple measurements were conducted within a single fire, message=FALSE, warning=FALSE, the entire fire was excluded from the training data used in the model training.}\label{fig:show-biplot-FFFC-new}
\end{figure}

Across the entire parameter space of Buildup Index and AGSlow pool size,
the following isolines of proportional consumption in the model can be
plotted:

\begin{figure}
\includegraphics[width=0.75\linewidth]{FFFC_surface_plot} \caption{Isoline contours of equal organic soil layer consumption fraction as a function of BUI and the organic soil layer Carbon pool in Mg C/ha.  Field observations of burn from 547 field measurements across Canada from the Yukon-Alaska border to Manitoba.  Rug plots at the axis margins show the marginal density of the data.}\label{fig:FFFC-surface-plot}
\end{figure}

\begin{figure}
\includegraphics[width=0.75\linewidth]{FFFC_expand_plot} \caption{Isoline contours of equal organic soil layer consumption fraction as a function of BUI and the organic soil layer Carbon pool in Mg C/ha.  Field observations of burn from 547 field measurements across Canada from the Yukon-Alaska border to Manitoba.}\label{fig:FFFC-plot-next}
\end{figure}

\newpage



\codedataavailability{This article was produced from an RMarkdown
document with underlying data, available at
https://github.com/nrcan-cfs-fire/FireDMs} %% use this section when having data sets and software code available



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% optional

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\competinginterests{The authors declare no competing
interests.} %% this section is mandatory even if you declare that no competing interests are present

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\disclaimer{The algorithm and results presented only apply to boreal and
temperate forest ecosystems where sufficient ground plots of fire
severity are available. As a data-driven model, this framework is not
suitable for other ecosystems nor agricultural or forestry biomass
burning practices.} %% optional section

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% REFERENCES
%% DN: pre-configured to BibTeX for rticles

%% The reference list is compiled as follows:
%%
%% \begin{thebibliography}{}
%%
%% \bibitem[AUTHOR(YEAR)]{LABEL1}
%% REFERENCE 1
%%
%% \bibitem[AUTHOR(YEAR)]{LABEL2}
%% REFERENCE 2
%%
%% \end{thebibliography}

%% Since the Copernicus LaTeX package includes the BibTeX style file copernicus.bst,
%% authors experienced with BibTeX only have to include the following two lines:
%%
\bibliographystyle{copernicus}
\bibliography{references.bib}
%%
%% URLs and DOIs can be entered in your BibTeX file as:
%%
%% URL = {http://www.xyz.org/~jones/idx_g.htm}
%% DOI = {10.5194/xyz}


%% LITERATURE CITATIONS
%%
%% command                        & example result
%% \citet{jones90}|               & Jones et al. (1990)
%% \citep{jones90}|               & (Jones et al., 1990)
%% \citep{jones90,jones93}|       & (Jones et al., 1990, 1993)
%% \citep[p.~32]{jones90}|        & (Jones et al., 1990, p.~32)
%% \citep[e.g.,][]{jones90}|      & (e.g., Jones et al., 1990)
%% \citep[e.g.,][p.~32]{jones90}| & (e.g., Jones et al., 1990, p.~32)
%% \citeauthor{jones90}|          & Jones et al.
%% \citeyear{jones90}|            & 1990


\end{document}
