%% Copernicus Publications Manuscript Preparation Template for LaTeX Submissions
%% ---------------------------------
%% This template should be used for copernicus.cls
%% The class file and some style files are bundled in the Copernicus Latex Package, which can be downloaded from the different journal webpages.
%% For further assistance please contact Copernicus Publications at: production@copernicus.org
%% https://publications.copernicus.org/for_authors/manuscript_preparation.html

%% copernicus_rticles_template (flag for rticles template detection - do not remove!)

%% Please use the following documentclass and journal abbreviations for discussion papers and final revised papers.

%% 2-column papers and discussion papers
\documentclass[, manuscript]{copernicus}



%% Journal abbreviations (please use the same for preprints and final revised papers)

% Advances in Geosciences (adgeo)
% Advances in Radio Science (ars)
% Advances in Science and Research (asr)
% Advances in Statistical Climatology, Meteorology and Oceanography (ascmo)
% Aerosol Research (ar)
% Annales Geophysicae (angeo)
% Archives Animal Breeding (aab)
% Atmospheric Chemistry and Physics (acp)
% Atmospheric Measurement Techniques (amt)
% Biogeosciences (bg)
% Climate of the Past (cp)
% DEUQUA Special Publications (deuquasp)
% Earth Surface Dynamics (esurf)
% Earth System Dynamics (esd)
% Earth System Science Data (essd)
% E&G Quaternary Science Journal (egqsj)
% EGUsphere (egusphere) | This is only for EGUsphere preprints submitted without relation to an EGU journal.
% European Journal of Mineralogy (ejm)
% Fossil Record (fr)
% Geochronology (gchron)
% Geographica Helvetica (gh)
% Geoscience Communication (gc)
% Geoscientific Instrumentation, Methods and Data Systems (gi)
% Geoscientific Model Development (gmd)
% History of Geo- and Space Sciences (hgss)
% Hydrology and Earth System Sciences (hess)
% Journal of Bone and Joint Infection (jbji)
% Journal of Micropalaeontology (jm)
% Journal of Sensors and Sensor Systems (jsss)
% Magnetic Resonance (mr)
% Mechanical Sciences (ms)
% Natural Hazards and Earth System Sciences (nhess)
% Nonlinear Processes in Geophysics (npg)
% Ocean Science (os)
% Polarforschung - Journal of the German Society for Polar Research (polf)
% Primate Biology (pb)
% Proceedings of the International Association of Hydrological Sciences (piahs)
% Safety of Nuclear Waste Disposal (sand)
% Scientific Drilling (sd)
% SOIL (soil)
% Solid Earth (se)
% State of the Planet (sp)
% The Cryosphere (tc)
% Weather and Climate Dynamics (wcd)
% Web Ecology (we)
% Wind Energy Science (wes)

% Pandoc citation processing

% The "Technical instructions for LaTex" by Copernicus require _not_ to insert any additional packages.
% 
% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}


%%\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
%
%% \usepackage commands included in the copernicus.cls:
%\usepackage[german, english]{babel}
%\usepackage{tabularx}
%\usepackage{cancel}
%\usepackage{multirow}
%\usepackage{supertabular}
%\usepackage{algorithmic}
%\usepackage{algorithm}
%\usepackage{amsthm}
%\usepackage{float}
%\usepackage{subfig}
%\usepackage{rotating}

\begin{document}


\title{Incorporating fire severity for refined data-drive carbon
emissions estimates of boreal and temperate forest fires in the Generic
Carbon Budget Model (GCBM)}


\Author[1][]{}{}
\Author[2]{}{}
\Author[3]{}{}
\Author[1]{}{}
\Author[3]{}{}
\Author[3]{}{}


\affil[1]{}
\affil[2]{}
\affil[3]{}

\runningtitle{Fire Severity and Forest Carbon Budget Models}

\runningauthor{Thompson et al.}


\correspondence{\ \ ()}



\received{}
\pubdiscuss{} %% only important for two-stage journals
\revised{}
\accepted{}
\published{}

%% These dates will be inserted by Copernicus Publications during the typesetting process.


\firstpage{1}

\maketitle


\begin{abstract}
Wildfire is the most impactful natural disturbance to Canada's boreal
and temperate forest biomes. Current representations of fire impact on
forest carbon stocks is limited to a single parameterization of fire
severity (i.e.~the fraction of biomass consumed) that assumes only high
severity fires, despite a large and increasing evidence base of
widespread mixed-severity wildfire. In this submodel of the larger
Generic Carbon Budget Model for forest carbon accounting, field
measurements of biomass consumption as related to satellite-derived burn
severity maps are interpretted from a fire physics and ecology
perspective to derive algorithms to describe forest carbon fluxes in the
immediate aftermath of fires.
\end{abstract}


\copyrightstatement{His Majesty the King in Right of Canada as
represented by the Minister of Natural Resources Canada. This work is
distributed under the Creative Commons Attribution 4.0 License.}


\section{Introduction}

general introduction on forest carbon accounting in Canada (1-2
paragraphs) and the concept of fire severity overall, and how these two
relate. Managed vs unmanaged forest natural disturbance accounting in
Canada, explain that part.

Wildfire is on par with insects as the largest stand-replacing
disturbance process in Canada's forest, impacting \textasciitilde1-3 Mha
of Canada's 355 Mha forested area in a typical year \citep{hanes2019}.
In Canada's reliable 40-year burned area record, six years have exceeded
4 Mha of burned area, largely in continental boreal and dry temperate
forests west of the Great Lakes. Of this, managed forest accounts for
xxx\% of the area burned between 1980 and 2022; publicly-owned forest
under long-term licence to private timber companies forms the vast
majority of Canada's managed forest \citep{stinson2019}, allowing for
simplified and harmonized forest inventory and carbon modelling across
jurisdictions (ref??). Burned area is dominated by a relatively small
number of very large fires, with 3\% of fires constituting 97\% of the
burned area \citep{stocks2002}. Lightning-caused fires account for
approximately half of all ignitions and between xxx and xxxx\% of burned
area, but no distinction is made between human and lightning ignition
for carbon accounting purposes. Annual burned area mapping at 30 metre
resolution is conducted using a composite of satellite and aerial
mapping; the relatively small number of large fires, and their slow
vegetation regeneration \citep{white2017} allows for reliable mapping
using multispectral imagery such as Landsat within the year of the fire
\citep{whitman2018}.

In CBM-CFS, spatially referenced stand lists representing large
homogenous stands that fall within spatial units (ecozone-provincial
intersections) are randomly (??) drawn, even when applying precisely
mapped burned areas. In Canada's forests, a combination of disturbance
history (), soils, and less frequently topographic variables determine
leading tree species; at local scales (1-100 ha), tree species plays a
major role in determining ecosystem susceptibility to fire
\citep{bernier2016} where older, conifer-dominated forests burn at very
high rates relative to adjacent deciduous or mixed stands. Even when
deciduous and mixed forests do burn, they do so at consistently lower
severity compared to all but the most xeric conifer forests
\citep{whitman2018}. Currently, biomass consumption estimates are based
on observed fire weather (and modelled using the Canadian Fire Behaviour
Prediction Systems) at the time of satellite fire activity detection,
but applied only at this spatially-referenced aggregated scale. Thus,
important biases in fire activity towards older and moderate to
poorly-drained forests are not resolved, and only a regionally-averaged
fire severity is applied.

To support recent advances in operational burn severity mapping for
Canada \citep{whitman2020} alongside multi-decade reliable burned area
records that provide certainty on fire start and end dates
\citep{hall2020} , the CBM DMs also need to be upgraded.

something about dynamic veg models like landis and how they represent
fire disturbance -then how most MRV models and quickly how they do fire
disturbance -even a bit on the GFED/GFAS world too

that ESSD frames it well, worth reading the intro part in detail)
(recent Smyth and Campbell papers too) (other recent Canadian
fire-carbon things, Walker - esp is supports consistent patterns in
proportional carbon loss)

In this document, we outline the evidence-based fire Disturbance
Matrices updated and designed for a spatially-explicit update to the
CBM, anchored in a three severity class paradigm. These fire carbon flux
models are built from a blend of aggregated field data linked to
remotely sensed severity, as well as insights from fire physics and
experimental fires. Key knowledge gaps are also highlighted, with
interim solutions presented until further quantification can be done in
field studies, such as from further wildfire observations, experimental
fires, or prescribed fires.

\section{Methods}

\subsection{Biomass pools of the Generic Carbon Budget Model}

Short section explaining the pool definitions most relevant to fire.

\subsection{Axioms of forest carbon budget after fire}

To simplify the process of the creation of the DMs as a distillation of
the complexities of fire severity and combustion patterns, the following
logical axioms are proposed and maintained throughout:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Disturbance matrices are to be in terms of mortality, not survival
\item
  Crown Fraction Burned (CFB) is a mass-based estimate of the portion of
  foliage consumed in flaming, and is inclusive of merchantable and
  submerchantable trees, both broadleaf and needleleaf
\item
  Snags are inclusive of both those killed by prior fire as well as
  those killed by all other causes
\item
  In submerchantable trees, mortality = CFB
\item
  In submerchantable trees, mortality is \textless= 1
\item
  In merchantable stands, CFB \textless{} mortality
\item
  Survival = 1 - mortality
\item
  CFB \textless{} survival
\item
  The girdled fraction of trees = mortality - CFB
\item
  Survival \textless= 1 and also \textgreater= 0
\end{enumerate}

Of these, Crown Fraction Burned (CFB) is both highly critical and a
concept used primarily in fire behaviour science but not carbon
accounting nor fire ecology. CFB was introduced in the 1992 Fire
Behaviour Prediction System documentation, and provides a simple
continuous 0-100 variable for only the consumption of foliage (inclusive
of both conifer and broadleaf), as opposed to ordinal and less precise
systems like Crown Fire Severity Index that allows the user to specify
moreso which pools of canopy biomass are consumed, but not the degree to
which a given pool is consumed.

\subsection{Ground plot and remotely sensed fire severity data}

!!!Ellen to insert methods here - including the figure of where the
samples are from etc.

\subsection{Combustion gas emission ratios}

Certain variables, like the fractionation of CO2:CH4:CO, are constant
throughout ecozones, but vary by flaming vs smouldering. They are
defined in a global variables table:

\begin{table}
\centering
\caption{\label{tab:globalVarsEmissions}Emissions factors in flaming and smouldering phase, expressed as portion of unburned biomass carbon content}
\centering
\begin{tabular}[t]{l|r|r}
\hline
Spp & Flaming & Smouldering\\
\hline
CO2 & 0.868 & 0.703\\
\hline
CO & 0.070 & 0.161\\
\hline
PM10 & 0.022 & 0.048\\
\hline
NMOG & 0.016 & 0.035\\
\hline
PM25 & 0.019 & 0.040\\
\hline
CH4 & 0.005 & 0.013\\
\hline
BC & 0.000 & 0.000\\
\hline
\end{tabular}
\end{table}

where CO\textsubscript{2} is responsible for 86.8\% of emissions in the
flaming phase, but only 70.3\% of emissions in the smouldering phase,
with a doubling of CO emissions and tripling of CH\textsubscript{4}
emissions. With a Global Warming Potential of CO equal to 1.9 and
CH\textsubscript{4} of 25, the Global Warming Potential per unit of
biomass consumption in the smouldering phase is 1.18 times higher in
global warming potential compared to flaming, not including differential
aerosol production and injection heights, however. Note that these
proposed emissions factors for flaming vs smouldering are aligned with
those currently used in Canada's operational wildfire smoke air quality
model, FireWork \citep{chen2019}. With flaming and smouldering each
contributing roughly equally to wildfire emissions, these distinct
flaming and smouldering emissions rates correspond well with aircraft
smoke chemistry observations by \citep{simpson2011} and
\citep{hayden2022} and are themselves very similar to prior emissions
factors used in CBM. Note that as current described, the sum of
CO\textsubscript{2}, CH\textsubscript{4}, and CO emissions from
wildfires only represent approximately 95\% of the fire carbon mass
emitted to the atmosphere, with 0.5-2.0\% of biomass emitted as
particulate matter (e.g.~PM2.5, but also PM1 and PM10 classes of
particulates at 1 and 10 um diameters, respectively), and an additional
3\% \citep{hayden2022} to as little as 1\% \citep{simon2010} composed of
non-methane organic gases that have a large range in global warming
potentials as compared to CH\textsubscript{4}.

\subsection{Litter layer area-wise consumption by severity class}

The litter layer forms the first biomass pool in which a spreading fire
consumes fuel. In low-severity fires, the litter layer may be consumed
little to no underlying duff material consumed, nor any tree mortality
\citep{hessburg2019}. Logically, since litter consumption is required
for the ignition of the underlying duff layer, this litter area-wise
fractional consumption also informs and constrains duff consumption.

\begin{table}
\centering
\caption{\label{tab:UnBurnedForestFloorByEcozone}Unburned litter area by ecozone and severity class.  The majority of the data comes from studies in the Boreal Plains and Boreal Shield West, and so values are extrapolated from those two well-observed ecozones to all others.}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.20 & 0.08 & 0.05\\
\hline
TP & 0.14 & 0.16 & 0.03\\
\hline
TSW & 0.20 & 0.08 & 0.05\\
\hline
BP & 0.14 & 0.06 & 0.02\\
\hline
BC & 0.14 & 0.06 & 0.02\\
\hline
BSE & 0.20 & 0.08 & 0.05\\
\hline
TSE & 0.20 & 0.08 & 0.05\\
\hline
MC & 0.14 & 0.06 & 0.02\\
\hline
HP & 0.20 & 0.08 & 0.05\\
\hline
TC & 0.14 & 0.06 & 0.02\\
\hline
PM & 0.14 & 0.06 & 0.02\\
\hline
AM & 0.14 & 0.06 & 0.02\\
\hline
MP & 0.14 & 0.06 & 0.02\\
\hline
P & 0.14 & 0.06 & 0.02\\
\hline
\end{tabular}
\end{table}

\subsection{Duff Consumption}

While consumption of fine fuels in the litter layer of the forest floor
is nearly complete for any given fire intensity, consumption of deeper
organic soil horizons (F+H layers in upland forests and upper peat
layers in wetlands) is more drought dependent. In the fire literature in
Canada, the soil organic layer is termed Forest Floor Fuel Load (FFFL)
and is dominated by the equivalent Belowground Slow pool (BGSlow) in
CBM. Typically attention has been paid to the absolute value of Forest
Floor Fuel Consumption (FFFC); however in the case of carbon modelling,
it is the relative fraction of consumption (FFFC/FFFL) that is of
interest. In this scheme, we utilize a composite of wildfire data from
\citep{degroot2009} alongside the ABoVE duff consumption data , with an
alternative modelling approach to compute the relative amount of depth
of consumption (scalar from 0 to 1) rather than an absolute value in
\unit{\,kg\,m^{-2}} or \unit{\,cm} as otherwise done in the literature.
A logit transform is used on the scalar data to make it suitable for the
fitted non-linear least-squares modelling:

\begin{equation}
logit \left( \frac{depth of burn}{prefire depth}\right) = [3.83(1 - e^{(-0.005DC)})] + (-0.718log_{e}(BGSlow))
\end{equation}

where DC is the Fire Weather Index Drought Code, and BGSlow in the CBM
(given in Mg C/ha in this equation), and also synonymous with the the
Forest Floor Fuel Load (with ecozone averages given in
\citep{letang2012} or site-level data where observed). The modelling of
relative depth of burn had a higher skill than modelling of the relative
mass of consumption, given natural variability in soil density with
depth.

A conversion factor is then applied to the relative depth of burn data
to convert it to a relative mass consumption value. Since organic soil
density always increases with depth, this conversion factor from depth
to mass is less than one:

\begin{equation}
\left( \frac{mass consumed}{prefire mass}\right) = \left( \frac{depth of burn}{prefire depth}\right) * CF
\end{equation}

where the Correction Factor is defined for boreal spruce fuel types as:

\begin{equation}
CF_{spruce} = 1.018(RelativeDepth)^0.250
\end{equation}

and for all other fuels as

\begin{equation}
CF_{nonspruce} = 0.13(RelativeDepth)+0.87
\end{equation}

with RelativeDepth as a value from 0-1.

While ultimately this scheme can be used on individual fires with
estimated or measured fuel loading and specific Drought Code values, for
the purposes of this first assessment, an ecozone-averaged fuel load and
decadal composites of Drought Code can also be used to provide
representative values. Specifically, a median Drought Code of detected
fire hotspots in Canada from 2003-2021 \citep{barber} using the same
data as the Canadian CFEEPS-FireWork wildfire air quality model of
\citep{chen2019} is presented below, along with proportional consumption
values of the forest floor by ecozone:

\begin{table}
\centering
\caption{\label{tab:DuffConsumpTable}Fire Weather, fuel loading, and duff consumption values per ecozone}
\centering
\begin{tabular}[t]{l|l|l|l|l}
\hline
Ecozone & Median Drought Code of Burning & Median FFFL kg m-2 & FFFC kg m-2 & \% consumption\\
\hline
BSW & 239 & 8.8 & 3.7 & 0.42\\
\hline
TP & 369 & 15 & 7.01 & 0.47\\
\hline
TSW & 297 & 1.7 & 1.33 & 0.78\\
\hline
BP & 242 & 9.8 & 3.96 & 0.4\\
\hline
BC & 250 & 8.31 & 3.72 & 0.45\\
\hline
BSE & 123 & 10.9 & 1.95 & 0.18\\
\hline
TSE & 98 & 1.7 & 0.71 & 0.42\\
\hline
MC & 452 & 6 & 4.15 & 0.69\\
\hline
HP & 204 & 7.9 & 3.02 & 0.38\\
\hline
TC & 254 & 8.31 & 3.77 & 0.45\\
\hline
PM & 268 & 15.2 & 5.45 & 0.36\\
\hline
AM & 270 & 10.9 & 4.62 & 0.42\\
\hline
P & 242 & 9.8 & 3.96 & 0.4\\
\hline
\end{tabular}
\end{table}

Note that the maximum upland Forest Floor Fuel Load is approximately 30
kg m-2 \citep{letang2012}; higher values are typically seen only in peat
ecosystems, where the above Forest Floor Fuel Consumption scheme does
not apply. For Canadian peatlands, the CaMP model \citep{bona2020} is
instead used in CBM. Within CaMP, a separate peatland water model driven
by Drought Code determines the thickness of the unsaturated peat layer,
and an amount approximating 12\% of the thickness of the unsaturated
peat is consumed as smouldering consumption. The peat-specific carbon
pools and fire Disturbance Matrices are fully described in
\citep{bona2020}; large peatland trees will still utilize the DM scheme
described below.

Little data is available on the fraction of woody debris consumption
alongside fire severity measurements. Coarse woody debris of overstory
stems that makes up 60-80\% of woody debris biomass in Canada's boreal
and temperate forests \citep{hanes2021}, with its moisture and
consumption patterns largely follows the moisture regime of the Drought
Code \citep{mcalpine1995}. In this modelling framework, the proportion
of coarse (\textgreater7.5 cm diameter) and medium (\textgreater0.5 cm
and \textless7.5 cm) woody debris consumption is estimated based on
detailed measurements of consumption from experimental fires. Coarse
Woody Debris is responsible for approximately 50-75\% of the total woody
debris load in most ecozones, and approximately 60\% of the total woody
debris consumption. Ecozone-level CWD consumption rates are summarized
as:

\begin{table}
\centering
\caption{\label{tab:CWDByEcozone}Coarse Woody debris consumption rates from pre/post measurements in experimental fires}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.024 & 0.163 & 0.140\\
\hline
TP & 0.000 & 0.218 & 0.238\\
\hline
TSW & 0.000 & 0.218 & 0.238\\
\hline
BP & 0.359 & 0.509 & 0.412\\
\hline
BC & 0.024 & 0.163 & 0.140\\
\hline
BSE & 0.080 & 0.131 & 0.182\\
\hline
TSE & 0.080 & 0.131 & 0.182\\
\hline
MC & 0.024 & 0.163 & 0.140\\
\hline
HP & 0.080 & 0.131 & 0.182\\
\hline
TC & 0.024 & 0.163 & 0.140\\
\hline
PM & 0.024 & 0.163 & 0.140\\
\hline
AM & 0.080 & 0.131 & 0.182\\
\hline
MP & 0.080 & 0.131 & 0.182\\
\hline
P & 0.359 & 0.509 & 0.412\\
\hline
\end{tabular}
\end{table}

Note that where historical burn severity data is not available, and
instead the fire classification type of surface, intermittent crowning,
and active crown fire are used as proxies for low, moderate, and high
severity fire, respectively. Fine woody debris \textless0.5 cm in
diameter is consumed at the exact same rate as the litter pool (see
section above).

\subsection{Drivers of C losses in the tree canopy}

\subsubsection{Overstory tree mortality and consumption}

Numerous process-driven \citep{michaletz2006} or empirical
\citep{hood2017} tree mortality models are present and show significant
skill in predicting tree mortality based on fire behaviour (i.e.~flame
length, rate of spread). Since the driving data in this model is
satellite-derived fire severity over the landscape scale, fire behaviour
metrics such as flame length or scorching height of bark are not
available as a continuous mapped product. Instead, softwood and hardwood
overstory mortality is calculated per ecozone as a function of
satellite-observed fire severity using aggregated ground plot data:

\begin{table}
\centering
\caption{\label{tab:MortByEcozone}Softwood fractional mortality by ecozone, as dervied from median values from field studies}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.45 & 0.81 & 1.00\\
\hline
TP & 0.45 & 0.81 & 1.00\\
\hline
TSW & 0.10 & 0.81 & 1.00\\
\hline
BP & 0.45 & 0.81 & 1.00\\
\hline
BC & 0.24 & 0.65 & 0.98\\
\hline
BSE & 0.45 & 0.81 & 1.00\\
\hline
TSE & 0.10 & 0.81 & 1.00\\
\hline
MC & 0.28 & 0.74 & 0.98\\
\hline
HP & 0.45 & 0.81 & 1.00\\
\hline
TC & 0.24 & 0.65 & 0.98\\
\hline
PM & 0.13 & 0.38 & 0.97\\
\hline
AM & 0.28 & 0.34 & 0.95\\
\hline
MP & 0.28 & 0.34 & 0.95\\
\hline
P & 0.45 & 0.81 & 1.00\\
\hline
\end{tabular}
\end{table}

And since large-diameter, live trees killed by fire do not experience
significant live stemwood consumption, the entirety of the live stemwood
biomass pool that is killed is transferred to the snag pool. Note that
the field data and disturbance modelling undertaken here only accounts
for tree mortality within the calender year of the fire, and delayed
mortality of over one year has been documented in boreal low and
moderate severity fires \citep{angers2011}where less than half of total
mortality occurs after the year of the fire. Thus, the modelling here
does not account for delayed mortality that may extend upwards of 5
years after fire.

Crown Fraction Burned (CFB) speaks to the fraction of the live canopy
that is itself consumed in the flaming front. The alternate outcomes
being survival of the foliage, or the mortality of the tree without
canopy consumption, resulting in the dropping of foliage onto the forest
floor. From the axioms stated earlier, the CFB must be lower than or
equal to the mortality rate, using field studies that show any partial
crown consumption is likely sufficient to result in high rates if not
complete mortality \citep{hood2017}, which is the case in Canada's trees
with primarily thin bark. Due to the structure of the CBM, all High
Severity fires have their mortality in the merchantable and smaller
trees set to exactly 1.0, which is no more than a 5\% variance from
observed values. From field studies, the following ecozone-specific CFB
values are found:

\begin{table}
\centering
\caption{\label{tab:CFBByEcozone}Softwood crown fraction burned by ecozone, as dervied from median values from field studies}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Ecozone & Low & Mod & High\\
\hline
BSW & 0.0 & 0.81 & 1.00\\
\hline
TP & 0.0 & 0.81 & 1.00\\
\hline
TSW & 0.1 & 0.81 & 1.00\\
\hline
BP & 0.0 & 0.81 & 1.00\\
\hline
BC & 0.0 & 0.65 & 0.98\\
\hline
BSE & 0.0 & 0.81 & 1.00\\
\hline
TSE & 0.1 & 0.81 & 1.00\\
\hline
MC & 0.0 & 0.74 & 1.00\\
\hline
HP & 0.0 & 0.81 & 1.00\\
\hline
TC & 0.0 & 0.65 & 1.00\\
\hline
PM & 0.0 & 0.38 & 0.97\\
\hline
AM & 0.0 & 0.34 & 0.95\\
\hline
MP & 0.0 & 0.34 & 0.95\\
\hline
P & 0.0 & 0.81 & 1.00\\
\hline
\end{tabular}
\end{table}

The consumption of live bark biomass is a pool in the model, and
consumption rates can be defined by severity class. At the moment,
lacking robust field data on bark biomass consumption rates across
ecozones and severity classes (which are a small portion of the overall
biomass), the bark proportional consumption rate is set to 34\% of the
overstory mortality rate, based only on a single set well-observed high
severity fires in the Taiga Plains by {[}santín2015{]}.

A major distinction is made between softwood and hardwood trees, where
in Canada's boreal forests, a large fraction of hardwood trees (see
Appendix E) are able to resprout even when the main stem has been killed
by an intense forest fire \citep{brown1987}. Accordingly, the root
mortality rates differ greatly between softwoods and hardwoods, with
softwood root mortality equal precisely to stem mortality, while in
resprouting hardwoods, little root mortality is observed even after
intense fire \citep{pérez-izquierdo2019}. Though GCBM can resolve a
species list down to the pixel level, currently an ecozone-level
regional average composition of hardwood species with resprouting traits
is used and is shown below:

\begin{table}
\centering
\caption{\label{tab:ReSproutByEcozone}Ecozone-level average fraction of hardwood overstory species that do not suffer extensive belowgroud biomass mortality after fire}
\centering
\begin{tabular}[t]{l|r}
\hline
Ecozone & Resprout Fraction\\
\hline
BSW & 0.75\\
\hline
TP & 0.75\\
\hline
TSW & 0.94\\
\hline
BP & 0.99\\
\hline
BC & 0.76\\
\hline
BSE & 0.67\\
\hline
TSE & 0.78\\
\hline
MC & 0.97\\
\hline
HP & 0.80\\
\hline
TC & 0.27\\
\hline
PM & 0.39\\
\hline
AM & 0.76\\
\hline
MP & 0.32\\
\hline
P & 0.99\\
\hline
\end{tabular}
\end{table}

Concurrently, the fraction of fine roots contained within the
combustible forest floor layers can be a close to or exceeding 50\% of
the fine root biomass \citep{strong1985}, and burns alongside the
organic soils \citep{benscoter2011}. As a result, the calulation for
softwood fine root consumption and mortality are as follows, using
Softwood as an example:

\begin{equation}
SWFineRootConsump = SW.Mort \times SW.Prop.Fine.Root.duff \times Duff.Consump.Fract
\end{equation}

\begin{equation}
SWFineRootMort.AG = SW.Mort \times SW.Prop.Fine.Root.duff \times (1-Duff.Consump.Fract) \times (1-ReSproutFactor)
SWFineRootMort.BG = SW.Mort \times (1-SW.Prop.Fine.Root.duff)
\end{equation}

In contrast, the larger diameter of the coarse root biomass pool
prevents its consumption during any smouldering of the duff layer, and
the mortality rate of coarse roots is simply proportional to that of the
stemwood overall.

\subsubsection{Understory tree mortality and consumption}

Understory (or small diameter overstory) tree mortality is defined
seperately in the model, but given the lack of data on diameter classes
in the severity data, robust field data on differing mortality rates of
smaller diameter trees is not available, and so the understory tree
mortality rate is set equal to the overstory rate as defined in the
table above. Note that trees with a top height less than 1.4 m are not
considered in this pool, and instead are lumped into the ``other'' pool.

\subsubsection{Snag and stump consumption}

Compared to live stemwood of the same diameter, the low moisture content
of standing dead stemwood (snags) allows for much greater consumption
during the passage of an intense flaming front. The snag branch pool
experiences almost complete combustion, while the largest biomass pool
of the main standing dead stemwood

\subsection{Construction fire disturbance matrices}

Give total number of global parameters, and parameters per ecozone, and
then total parameters, and what \% of total parameters we have so far
filled with data

\section{Results and example applications}

\begin{landscape}\begin{table}[!h]
\centering
\caption{\label{tab:makeTables}High severity Disturbance Matrix in BP}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{3cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}|>{\centering\arraybackslash}p{2cm}}
\hline
  & Softwood Merchantable & Softwood Stem Snag & Medium DOM
 & Softwood Foliage & Aboveground Very Fast DOM & CO2 & CH4 & CO & PM25\\
\hline
Softwood Merchantable & 0 & 1 &  &  &  &  &  &  & \\
\hline
Softwood Stem Snag &  & 0 & 0.90000 &  &  & 0.0868000 & 0.0005000 & 0.0070000 & 0.0019000\\
\hline
Medium DOM &  &  & 0.57624 &  &  & 0.2979033 & 0.0055089 & 0.0682254 & 0.0169504\\
\hline
Softwood Foliage &  &  &  & 0 & 0.00 & 0.8680000 & 0.0050000 & 0.0700000 & 0.0190000\\
\hline
Aboveground Very Fast DOM &  &  &  &  & 0.02 & 0.8506400 & 0.0049000 & 0.0686000 & 0.0186200\\
\hline
CO2 &  &  &  &  &  &  &  &  & \\
\hline
CH4 &  &  &  &  &  &  &  &  & \\
\hline
CO &  &  &  &  &  &  &  &  & \\
\hline
PM25 &  &  &  &  &  &  &  &  & \\
\hline
\end{tabular}}
\end{table}
\end{landscape}

\subsection{Field case studies (for consideration)}

\begin{verbatim}
### table with rows are CBM pools, columns (paird) are obs
### and modelled exp fires

### fires that would work:

### ICFME (SW TP High); Sharpsands 2007 (SW BSE High),
### Lafoe (HW BSE Low), CWS C-7 burns (SW MC Mod), Carrot
### lake (SW MC High)

### variables specifically measured during an experimental
### fire, in the verbiage of the fire DMs:
exp.fire.table.defs <- c("SW.CFB", "HW.CFB", "SW.Mort", "HW.Mort",
    "SW.SubMerch.Mort", "HW.SubMerch.Mort", "SmTree.Mort", "SW.Snag.Comb.Frac",
    "HW.Snag.Comb.Frac", "MedDOM.Comb.Frac", "Duff.consump.frac")

## then, take the list above, and look up the same row but
## the column 'Plain.Language.Name' in FireDMTableDefs.csv:
## exp.fire.table.labels <-

## note that Duff.consump.frac is an ecozone variable, not
## in FireDMTableDefs.csv

## list of all possible CBM pools measured during an
## experimental fire:
exp.fire.pools <- c("Softwood Foliage", "Softwood Other", "Aboveground Very Fast DOM",
    "Aboveground Fast DOM", "Medium DOM", "Aboveground Slow DOM",
    "Softwood Stem Snag", "Hardwood Other", "Hardwood Stem Snag")

### fun idea: ternary plots of live vs combusted vs dead
### for each of these fires, modelled vs observed?
### https://cran.r-project.org/web/packages/Ternary/vignettes/Ternary.html
### with the colour being the fuel type/leading spp and
### size being total emissions?  can we draw lines in
### between pairs of mod vs obs in that package? TernaryApp
### function in the package should apparently let you draw
### connected points?
\end{verbatim}

\section{Discussion}

-some discussion points (unordered) so far

\begin{itemize}
\tightlist
\item
  given the generic nature of these DMs and their simple relative
  simplicity, can be added to other frameworks like LANDIS (see Stenzel
  2019 as well, they do some of that).
\end{itemize}

\begin{itemize}
\tightlist
\item
  paragraph on extended impacts like delayed stem mortality, rapid snag
  fall, and changes (or not) in duff decomposition rates. Not (as of
  yet) covered in this 1-timestep pulse disturbance described here.
\end{itemize}

\section{Conclusions}

The conclusion goes here.

\section{Appendix A: list of fluxes and corresponding fire-related
plain-language summary.}

\section{Appendix B: non-linear least squares modelling of soil organic
layer consumption}

For national annual estimates of forest organic soil layer consumption
during wildfire, implementations that only utilize Canadian experimental
fire data from the Fire Behaviour Prediction System will be limited to a
maximum consumption value of 5 kg/m2 of total surface fuel (woody
debris, litter, and duff) of 5 kg/m2, or 25 Mg C/ha, given the
observation dataset and fitted model parameters. For the common C-2
Boreal Spruce fuel type for instance, Surface Fuel Consumption (kg m/2)
is modelled as:

\begin{equation}
SFC = 5.0 \left(1-e^{-0.0115BUI} \right)^{1.0}
\end{equation}                                             

This model form has the distinct advantage of SFC being 0.0 at a BUI of
zero. The model parameters vary by fuel type (i.e.~deciduous broadleaf
fuels are limited to 1.5 kg/m2 of maximum SFC) but are fixed within a
fuel type.

More recent observations and modelling from \citet{degroot2009} extended
the FBP data with an additional 128 observations from 7 additional
wildfires, and the ABoVE project compiled over 1000 field observations
of depth of burn and C stocks before and after wildfire in Canada and
Alaska, over 600 of which are in North American Level II ecoregions also
occurring in Canada (fix Walker 2020 ORNL DAAC ref in bibtex here).
\citet{degroot2009} provides a concise and informative improvement on
the FBP fuel consumption equations, where both a Fire Weather Index
System component (in this case, Drought Code) is used similarly to
Buildup Index in the FBP, but importantly, the site-level organic soil
layer fuel load is also accounted for, which allows for the greater
absolute combustion in deeper organic soils that is moderated by the
natural logarithm transformation:

\begin{equation}
log_{e}(FFFC) = -4.252+0.710log_{e}(DC) + 0.671log_{e}(FFFL)
\end{equation}

where FFFC is Forest Floor Fuel Consumption (SFC minus surface woody
debris) in kg m/2 and FFFL is Forest Floor Fuel Load in kg/m2. This
model fits well within the dataset and extends the observed maximum FFFC
to nearly 10 kg/m2. The ABoVE synthesis of FFFL and FFFC (Walker et al
2020 ORNL) expands upon a slightly smaller dataset used in a modelling
summary also by Walker et al (2020 NCC), where structural equation
modelling was used to explore drivers of FFFC but no concise and readily
reproducible modelling is produced. The results of the SEM from Walker
et al (2020 NCC) emphasized a greater role of FFFL over DC, though
coarse reanalysis that lacked local fire agency weather stations was
used. An analysis of just 2014 fires in the Northwest Territories by
(walker2018) showed that while the mean depth of burn across all black
spruce stands was 6-10 cm, the driest (xeric) black spruce stands with
the smallest FFFL showed upwards of 75\% soil organic consumption, while
deeper organic soils in subhygric black spruce stands showed less than
25\% consumption.

To provide the largest possible dataset for FFFC and FFFL, the ABoVE
synthesis was combined with wildfire data from de Groot et al 2009 not
otherwise found in the ABoVE synthesis. The ABoVE synthesis sites in the
Alaska Boreal Interior ecoregion, which have equivalent Canadian ecozone
were excluded, but Alaska Boreal Cordillera sites near the Yukon border
were utilized. Experimental fire data from the FBP data was not used, as
deeper combustion measurements resulting from hours and days of
smouldering combustion captured in wildfire data are not available in
experimental fires where extensive smouldering is not measured due to
suppression. In order to best represent on-the-ground Fire Weather Index
values, the Drought Code and other FWI values from Walker et al 2020
reanalysis were substituted with interpolated weather station (both
Environment and Climate Change Canada as well fire agency stations).
This data also has the benefit of being properly overwintered for
Drought Code (Hanes DC overwinter) and capturing small rain events not
captured in reanalysis that meaningfully impact the Duff Moisture Code
in particular.

For the purposes of improving national estimates of the fractional soil
organic layer loss during wildfire, this framework emphasizes the
proportional C stock loss (as with all CBM disturbance matrices) rather
than the absolute value of combustion. In contrast to the modelling of
absolute combustion value, any analysis of proportions is best conducted
as logit- transformed data, where the logit transformation is:

\begin{equation}
logit(p) = log\frac{p}{1-p}
\end{equation}

which effectively transforms a data of proportions of {[}0,1{]} to a
Gaussian distribution with a range of approximately -5 to +5 (in this
dataset), and a mode approximately at zero. Within the logit-transformed
data, exploratory analysis of ecozones as a factor alongside other
non-linear splines of FWI values and FFFL was conducted:

\begin{verbatim}
## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## prop_sol_combusted_logit ~ s(drought_code, k = 4, bs = "tp") + 
##     ecozone + s(BGSlow.Mg.C.ha, k = 4, bs = "tp")
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(>|t|)  
## (Intercept)  0.11939    0.09318   1.281   0.2005  
## ecozoneBP   -0.29433    0.15506  -1.898   0.0581 .
## ecozoneBSW  -0.19928    0.15988  -1.246   0.2131  
## ecozoneTP   -0.23049    0.11476  -2.008   0.0450 *
## ecozoneTSW  -0.29887    0.12157  -2.458   0.0142 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##                     edf Ref.df       F p-value    
## s(drought_code)   1.352  1.618   2.862  0.0631 .  
## s(BGSlow.Mg.C.ha) 2.950  2.998 232.720  <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  0.628   Deviance explained = 63.3%
## -REML = 869.04  Scale est. = 0.81207   n = 651
\end{verbatim}

(could also show boxplots?) which shows that the Boreal Cordillera
ecozone has a meaningfully higher proportional soil organic layer
consumption rate compared to BP, BSW, TP, and TSW, all of which are not
significantly different in consumption rates once DC and FFFC (shown as
BGSlow.Mg.C.ha) are accounted for. Boreal Cordillera data were set aside
for a distinct model.

Similar to \citet{degroot2009}, Drought Code was a better predictor of
consumption rates than Buildup Index as used in the FBP. In the logit
transformed space, saturation-type non-linear curve using the relevant
FWI component was fitted in a non-linear least squares model, but an
additive term of the natural-logarithm transformed FFFC (given as BGSlow
pool in Mg C/ha) was used as well. In the end, a superior model was
found using the proportional depth of burn, rather than the proportional
loss of the mass of the soil organic layer. The non-linear least squares
model fit was conducted using the Levenberg-Marquardt nonlinear
least-squares algorithm found in MINPACK (Elzhov et al 2023) R package,
which supported bounded parameter constraints. In the abstract, the
model follows the form:

\begin{equation}
logit \left( \frac{depth of burn}{pre-fire organic depth}\right) = [3.83*(1 - e^{(-0.005 * DC)})] + (-0.718*log_{e}(BGSlow))
\end{equation}

In the abstract, the model follows the form:

\begin{equation}
logit \left( \frac{depth of burn}{pre-fire organic depth}\right) = [c*(1 - e^{(a * DC)})] + (b*log_{e}(BGSlow))
\end{equation}

Note the ``b'' coefficient on the parameter associated with the FFFL
(BGSlow) of -0.718, which results in larger organic layer fuel loads
leading to smaller proportional consumption values, which follows the
patterns shown by Walker 2018 for NWT fires of 2014.

The a parameter term that forms the exponent of e alongside Drought Code
is related to the DC value at which half of the maximum possible
asymptotal consumption value is observed (for a given FFFL value). The
NLS fitting was given a minimum value of -0.06 such that half of the
asymptotal maximum consumption rate was modelled as occurring at or
around a DC value of 300. The other parameters were fit to the best
possible value with no constraint.

Importantly, since fire behaviour, emissions modelling, and carbon
accounting all operate with the calculation of mass loss and depth of
burn, a correction factor was applied that corrects for the trends in
bulk density with depth for C-2 fuels as given by \citet{degroot2009},
so that a model of proportional depth of burn is then converted into a
proportional mass loss term:

\begin{equation}
\left( \frac{FFFC}{FFFL}\right) = 1.017 \left( \frac{depth of burn}{pre-fire organic depth}\right)^{0.250}
\end{equation}

which for example means that the median proportional depth of burn in
the AboVE/de Groot training data of 0.40 corresponds to 0.32 of the
proportional mass loss (since shallow organic soil is less dense), or a
correction factor of 0.80. For non-spruce-dominated fuels, this
correction is much smaller but still meaningful:

\begin{equation}
\left( \frac{FFFC}{FFFL}\right) = 0.13 \left( \frac{depth of burn}{pre-fire organic depth}\right)+0.87
\end{equation}

(show perhaps what a few different a values look like?) (also compute
the DC value of about half the maximum FBP SFC values too, just for
kicks)

For example, using a moderately thick \textasciitilde12 cm thick organic
soil layer, the proportion of consumption as a function of Drought Code
using the model above

\includegraphics{GMD-Thompson-et-al_files/figure-latex/example-FFFC-vs-DC-plot-nls-1.pdf}

With the parameter constrained NLS fitting, the proportional consumption
model for the forest floor has a leave-one-out (conducted at the
fire-level, not plot) cross validated r2 of \#\#\#, and a Mean Percent
Error of \#\#\#\%

\begin{verbatim}
## Scale for y is already present.
## Adding another scale for y, which will replace the existing scale.
## Scale for y is already present.
## Adding another scale for y, which will replace the existing scale.
## Scale for x is already present.
## Adding another scale for x, which will replace the existing scale.
\end{verbatim}

\includegraphics{GMD-Thompson-et-al_files/figure-latex/show-biplot-FFFC-new-1.pdf}

Across the entire parameter space of Drought Code and BGSlow pool size,
the following isolines of proportional consumption in the model can be
plotted:

\includegraphics{GMD-Thompson-et-al_files/figure-latex/FFFC-surface-plot-1.pdf}

\includegraphics{GMD-Thompson-et-al_files/figure-latex/correction-factor-1.pdf}

\subsubsection{Boreal Cordillera modelling}

For the Boreal Cordillera, a simple linear model on the
logit-transformed data was found to be the best performing model for
estimating soil organic consumption proportion:

\begin{equation}
logit \left( \frac{FFFC}{FFFL}\right) = (0.00257 * DC) + (-0.54 * log_{e}(BGSlow)) + 2.17
\end{equation}

Despite the presence of a fixed intercept term, the strong inverse
dependence on the natural logarithm of the BGSlow pool size (FFFL)
results in zero proportional consumption when Drought Code is equal to
zero.

\section{Appendix C: annual variability in observed Drought Code during
wildfire spread, and impact on ecozone-level DM calculations}

\subsubsection{(Currently not running, needs model update)}

\section{Appendix \#\#\#: DM template (can delete in final draft)}

First, a generic template for a fire DM is loaded, that can represent
any ecozone. It comes in two parts: (1) a list of variables, some
biophysical and not relating to fire severity (such as the portion of
live branchwood that falls into the smaller size fraction); or (2)
severity-specific variables (such as Crown Fraction Burn) for a severity
class. The template is loaded, and replicated across the list of
ecozones (or any spatial unit) desired. Other processes, such as the
analysis of field data, can then be used to fill in ecozone-specific
variables in severity classes.

An example of the variable definition template is as follows:

\begin{table}[!h]
\centering\centering\centering
\caption{\label{tab:varDefsExample}Example of stored fire disturbance matrix precursor variable information}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|l|l|l|r|l|l|l}
\hline
Ecozone & Pool & Plain.Language.Name & Variable.Name & Value & SeverityClass & InterimValue & Notes\\
\hline
AM & AGFastDOM & Woody Debris Portion of AGFastDOM & CWD.frac.of.AGFastDOM & 0.5 &  & TRUE & \\
\hline
BC & AGFastDOM & Woody Debris Portion of AGFastDOM & CWD.frac.of.AGFastDOM & 0.5 &  & TRUE & \\
\hline
BP & AGFastDOM & Woody Debris Portion of AGFastDOM & CWD.frac.of.AGFastDOM & 0.5 &  & TRUE & \\
\hline
BSW & AGFastDOM & Woody Debris Portion of AGFastDOM & CWD.frac.of.AGFastDOM & 0.5 &  & TRUE & \\
\hline
BSE & AGFastDOM & Woody Debris Portion of AGFastDOM & CWD.frac.of.AGFastDOM & 0.5 &  & TRUE & \\
\hline
HP & AGFastDOM & Woody Debris Portion of AGFastDOM & CWD.frac.of.AGFastDOM & 0.5 &  & TRUE & \\
\hline
\end{tabular}}
\end{table}

A plain language name for each variable is provided right in the data,
as well.

A second template defines each flux in a Disturbance Matrix, with Source
and Sink defined as precise character variables, and a plain language
summary (``Process Synonym'') included to tie this flux back to language
used in the fire science literature. Pseudocode and notes are included
in each flux, which is repeated for each fire severity class and
ecozone. There are 3900 total fluxes, though many do not have sufficient
information to describe differences between ecozones. Many of these are
computed automatically, tying back into variables such as Crown Fraction
Burned.

\begin{table}[!h]
\centering\centering\centering
\caption{\label{tab:SinkSourceExample}Sample of disturbance matrix data file}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|r|l|l|l|l|r|l|l|l|r|l}
\hline
Ecozone & FluxID & Source & Sink & ProcessSynonym & Phase & CORefFluxID & Pseudocode & Notes & SeverityClass & Value & InterimValue\\
\hline
BSW & 1 & Softwood Merchantable & Softwood Merchantable & Survival rate of large conifers &  &  & 1-mortality rate & Ellen provides & Low & 1.0 & TRUE\\
\hline
TP & 1 & Softwood Merchantable & Softwood Merchantable & Survival rate of large conifers &  &  & 1-mortality rate & Ellen provides & Low & 1.0 & TRUE\\
\hline
TSW & 1 & Softwood Merchantable & Softwood Merchantable & Survival rate of large conifers &  &  & 1-mortality rate & Ellen provides & Low & 0.9 & TRUE\\
\hline
BP & 1 & Softwood Merchantable & Softwood Merchantable & Survival rate of large conifers &  &  & 1-mortality rate & Ellen provides & Low & 1.0 & TRUE\\
\hline
BC & 1 & Softwood Merchantable & Softwood Merchantable & Survival rate of large conifers &  &  & 1-mortality rate & Ellen provides & Low & 1.0 & TRUE\\
\hline
BSE & 1 & Softwood Merchantable & Softwood Merchantable & Survival rate of large conifers &  &  & 1-mortality rate & Ellen provides & Low & 1.0 & TRUE\\
\hline
\end{tabular}}
\end{table}

With both generic ecozone variables as well as severity-specific
variables defined and the pseudocode for each flux included, actual DM
values are computed as references to tables, subset by ecozone and
severity class.

Note that rather than defining softwood crown fraction burned as a
variable called ``SW.CFB.Boreal.Plains'' for each ecozone, there is a
row in the VarDefs table that represents SW.CFB in each ecozone and for
each severity class, thus avoiding the creation of large lists of
manually entered variable names and values in the R environment.
Instead, these values can be programmatically entered via external
analysis of plot data (not covered here).

\section{Appendix D: Representative photos}

Photos of: (1) partial litter consumption; (2) partial vs full duff
consumption; (3) mortality but not consumption of understory trees with
live overstory; (4) mortality but not consumption of overstory trees;
(5) mixedwood severity example showing consumption of broadleaf foliage;
(6) woody debris consumption; (7) snag preferential consumption relative
to little to no bole consumption in live trees

Give lat/long, year, ecozone, severity class, and leading spp for each
photo, maybe other relevant metrics? From some of the experimental fires
mostly??

\section{Appendix E: List of Resprouting Hardwoods of Canada}

Alnus spp. Arbutus men. Betula all. Betula pap. Betula pop. Fraxinus
ame. Fraxinus nig. Fraxinus pen. Populus bal. Populus gra. Populus tre.
Populus tri. Quercus spp. Salix spp.



\codedataavailability{This article was produced from an RMarkdown
document with underlying data, available at
https://github.com/nrcan-cfs-fire/FireDMs} %% use this section when having data sets and software code available



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% optional

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\appendix
\section{List of fluxes and corresponding fire-related plain-language summary}

Regarding figures and tables in appendices, the following two options
are possible depending on your general handling of figures and tables in
the manuscript environment:

\subsection{Option 1}

If you sorted all figures and tables into the sections of the text,
please also sort the appendix figures and appendix tables into the
respective appendix sections. They will be correctly named
automatically.

\subsection{Option 2}

If you put all figures after the reference list, please insert appendix
tables and figures after the normal tables and figures.

To rename them correctly to A1, A2, etc., please add the following
commands in front of them: \texttt{\textbackslash{}appendixfigures}
needs to be added in front of appendix figures
\texttt{\textbackslash{}appendixtables} needs to be added in front of
appendix tables

Please add \texttt{\textbackslash{}clearpage} between each table and/or
figure. Further guidelines on figures and tables can be found below.
\noappendix

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\authorcontribution{Thompson and Whitman contributed to the concept and
code design with the assistance of Hanes, Hudson} %% optional section

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\competinginterests{The authors declare no competing
interests.} %% this section is mandatory even if you declare that no competing interests are present

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\disclaimer{The algorithm and results presented only apply to boreal and
temperate forest ecosystems where sufficient ground plots of fire
severity are available. As a data-driven model, this framework is not
suitable for other ecosystems nor agricultural or forestry biomass
burning practices.} %% optional section

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{acknowledgements}
Thanks to (insert names here)
\end{acknowledgements}

%% REFERENCES
%% DN: pre-configured to BibTeX for rticles

%% The reference list is compiled as follows:
%%
%% \begin{thebibliography}{}
%%
%% \bibitem[AUTHOR(YEAR)]{LABEL1}
%% REFERENCE 1
%%
%% \bibitem[AUTHOR(YEAR)]{LABEL2}
%% REFERENCE 2
%%
%% \end{thebibliography}

%% Since the Copernicus LaTeX package includes the BibTeX style file copernicus.bst,
%% authors experienced with BibTeX only have to include the following two lines:
%%
\bibliographystyle{copernicus}
\bibliography{references.bib}
%%
%% URLs and DOIs can be entered in your BibTeX file as:
%%
%% URL = {http://www.xyz.org/~jones/idx_g.htm}
%% DOI = {10.5194/xyz}


%% LITERATURE CITATIONS
%%
%% command                        & example result
%% \citet{jones90}|               & Jones et al. (1990)
%% \citep{jones90}|               & (Jones et al., 1990)
%% \citep{jones90,jones93}|       & (Jones et al., 1990, 1993)
%% \citep[p.~32]{jones90}|        & (Jones et al., 1990, p.~32)
%% \citep[e.g.,][]{jones90}|      & (e.g., Jones et al., 1990)
%% \citep[e.g.,][p.~32]{jones90}| & (e.g., Jones et al., 1990, p.~32)
%% \citeauthor{jones90}|          & Jones et al.
%% \citeyear{jones90}|            & 1990


\end{document}
